package libc

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/goplus/llgo/internal/crosscompile/compile"
)

var _libcLDFlags = []string{
	"-nostdlib",
	"-ffunction-sections",
	"-fdata-sections",
}

var _libcCCFlags = []string{
	"-Oz",
	"-fno-builtin",
	// freestanding tells compiler this is a baremental project
	"-ffreestanding",
}

// withDefaultCCFlags appends default C compiler flags to the provided flags
func withDefaultCCFlags(ccflags []string) []string {
	return append(ccflags, _libcCCFlags...)
}

func joinFileList(root, files string) []string {
	items := strings.Fields(files)
	paths := make([]string, 0, len(items))
	prefix := root
	if prefix != "" {
		prefix = filepath.Clean(prefix)
		if !strings.HasSuffix(prefix, string(os.PathSeparator)) {
			prefix += string(os.PathSeparator)
		}
	}
	for _, item := range items {
		paths = append(paths, prefix+filepath.FromSlash(item))
	}
	return paths
}

// GetNewlibESP32Config returns the configuration for downloading and building newlib for ESP32
func GetNewlibESP32Config() compile.LibConfig {
	return compile.LibConfig{
		Url:            "https://github.com/goplus/newlib/archive/refs/tags/esp-4.3.0_20250211-patch7.tar.gz",
		Name:           "newlib-esp32",
		Version:        "esp-4.3.0_20250211-patch7",
		ResourceSubDir: "newlib-esp-4.3.0_20250211-patch7",
	}
}

// getNewlibESP32ConfigRISCV returns RISCV newlib compile groups.
//
// Note on float formatted I/O:
// goplus/newlib README (`--enable-newlib-nano-formatted-io`) documents that
// float printf/scanf support is gated by weak symbols and must be requested
// explicitly via linker `-u _printf_float` / `-u _scanf_float`
// (single-arg equivalent: `--undefined=_printf_float`).
// Therefore this config does not inject this flag here; it must be
// declared by the external target/link config (for esp32c3-basic see
// targets/esp32c3-basic.json).
func getNewlibESP32ConfigRISCV(baseDir, target string) compile.CompileConfig {
	libcDir := filepath.Join(baseDir, "newlib", "libc")

	libcIncludeDir := []string{
		"-isystem" + filepath.Join(libcDir, "include"),
		"-I" + filepath.Join(baseDir, "newlib"),
		"-I" + libcDir,
	}

	libmCommonCFlags := []string{
		"-DHAVE_CONFIG_H",
		"-D_LIBC",
		"-DHAVE_NANOSLEEP",
		"-D_NO_GLOB",
		"-D_NO_EXECVE",
		"-D_NO_GETLOGIN",
		"-D_NO_GETPWENT",
		"-D_NO_GETUT",
		"-D_NO_GETPASS",
		"-D_NO_SIGSET",
		"-D_NO_WORDEXP",
		"-D_NO_POPEN",
		"-D_NO_POSIX_SPAWN",
		"-DHAVE_FCNTL",
		"-DHAVE_BLKSIZE",
		"-DHAVE_OPENDIR",
		"-DHAVE_RENAME",
		"-DGETREENT_PROVIDED",
		"-DSIGNAL_PROVIDED",
		"-D__ESP__",
		"-isystem" + filepath.Join(libcDir, "include"),
		"-I" + filepath.Join(baseDir, "newlib"),
		"-idirafter" + filepath.Join(baseDir, "include"),
		"-I" + filepath.Join(baseDir, "newlib", "libm", "common"),
	}
	return compile.CompileConfig{
		ExportCFlags: libcIncludeDir,
		Groups: []compile.CompileGroup{
			{
				OutputFileName: "libsemihost-" + target + ".a",
				Files: joinFileList(baseDir, `
libgloss/riscv/semihost-sys_exit.c
				`),
				CFlags: []string{
					"-DHAVE_CONFIG_H",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					"-I" + filepath.Join(baseDir, "libgloss", "riscv"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
			{
				OutputFileName: "libcrt0-" + target + ".a",
				Files: joinFileList(baseDir, `
libgloss/riscv/esp/esp_board.c
libgloss/riscv/esp/syscalls.c
libgloss/riscv/esp/crt1-board.S
				`),
				CFlags: []string{
					"-DHAVE_CONFIG_H",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					// TODO(MeteorsLiu): support riscv
					"-I" + filepath.Join(baseDir, "libgloss", "riscv"),
					"-I" + filepath.Join(baseDir, "libgloss", "riscv", "esp"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
			{
				OutputFileName: "libgloss-" + target + ".a",
				Files: joinFileList(baseDir, `
libgloss/libnosys/chown.c
libgloss/libnosys/close.c
libgloss/libnosys/environ.c
libgloss/libnosys/errno.c
libgloss/libnosys/execve.c
libgloss/libnosys/fork.c
libgloss/libnosys/fstat.c
libgloss/libnosys/getpid.c
libgloss/libnosys/gettod.c
libgloss/libnosys/isatty.c
libgloss/libnosys/kill.c
libgloss/libnosys/link.c
libgloss/libnosys/lseek.c
libgloss/libnosys/open.c
libgloss/libnosys/read.c
libgloss/libnosys/readlink.c
libgloss/libnosys/sbrk.c
libgloss/libnosys/stat.c
libgloss/libnosys/symlink.c
libgloss/libnosys/times.c
libgloss/libnosys/unlink.c
libgloss/libnosys/wait.c
libgloss/libnosys/write.c
libgloss/libnosys/getentropy.c
libgloss/libnosys/getreent.c
libgloss/libnosys/time.c
libgloss/libnosys/fcntl.c
libgloss/libnosys/chdir.c
libgloss/libnosys/chmod.c
libgloss/libnosys/closedir.c
libgloss/libnosys/dirfd.c
libgloss/libnosys/ftw.c
libgloss/libnosys/getcwd.c
libgloss/libnosys/mkdir.c
libgloss/libnosys/nftw.c
libgloss/libnosys/opendir.c
libgloss/libnosys/pathconf.c
libgloss/libnosys/readdir.c
libgloss/libnosys/rewinddir.c
libgloss/libnosys/scandir.c
libgloss/libnosys/seekdir.c
libgloss/libnosys/telldir.c
libgloss/libnosys/rename.c
libgloss/libnosys/_pthread_cleanup_pop.c
libgloss/libnosys/_pthread_cleanup_pop_restore.c
libgloss/libnosys/_pthread_cleanup_push.c
libgloss/libnosys/_pthread_cleanup_push_defer.c
libgloss/libnosys/pthread_atfork.c
libgloss/libnosys/pthread_attr_destroy.c
libgloss/libnosys/pthread_attr_getaffinity_np.c
libgloss/libnosys/pthread_attr_getdetachstate.c
libgloss/libnosys/pthread_attr_getguardsize.c
libgloss/libnosys/pthread_attr_getinheritsched.c
libgloss/libnosys/pthread_attr_getschedparam.c
libgloss/libnosys/pthread_attr_getschedpolicy.c
libgloss/libnosys/pthread_attr_getscope.c
libgloss/libnosys/pthread_attr_getstack.c
libgloss/libnosys/pthread_attr_getstackaddr.c
libgloss/libnosys/pthread_attr_getstacksize.c
libgloss/libnosys/pthread_attr_init.c
libgloss/libnosys/pthread_attr_setaffinity_np.c
libgloss/libnosys/pthread_attr_setdetachstate.c
libgloss/libnosys/pthread_attr_setguardsize.c
libgloss/libnosys/pthread_attr_setinheritsched.c
libgloss/libnosys/pthread_attr_setschedparam.c
libgloss/libnosys/pthread_attr_setschedpolicy.c
libgloss/libnosys/pthread_attr_setscope.c
libgloss/libnosys/pthread_attr_setstack.c
libgloss/libnosys/pthread_attr_setstackaddr.c
libgloss/libnosys/pthread_attr_setstacksize.c
libgloss/libnosys/pthread_barrier_destroy.c
libgloss/libnosys/pthread_barrier_init.c
libgloss/libnosys/pthread_barrier_wait.c
libgloss/libnosys/pthread_barrierattr_destroy.c
libgloss/libnosys/pthread_barrierattr_getpshared.c
libgloss/libnosys/pthread_barrierattr_init.c
libgloss/libnosys/pthread_barrierattr_setpshared.c
libgloss/libnosys/pthread_cancel.c
libgloss/libnosys/pthread_cond_broadcast.c
libgloss/libnosys/pthread_cond_clockwait.c
libgloss/libnosys/pthread_cond_destroy.c
libgloss/libnosys/pthread_cond_init.c
libgloss/libnosys/pthread_cond_signal.c
libgloss/libnosys/pthread_cond_timedwait.c
libgloss/libnosys/pthread_cond_wait.c
libgloss/libnosys/pthread_condattr_destroy.c
libgloss/libnosys/pthread_condattr_getclock.c
libgloss/libnosys/pthread_condattr_getpshared.c
libgloss/libnosys/pthread_condattr_init.c
libgloss/libnosys/pthread_condattr_setclock.c
libgloss/libnosys/pthread_condattr_setpshared.c
libgloss/libnosys/pthread_create.c
libgloss/libnosys/pthread_detach.c
libgloss/libnosys/pthread_equal.c
libgloss/libnosys/pthread_exit.c
libgloss/libnosys/pthread_getaffinity_np.c
libgloss/libnosys/pthread_getattr_np.c
libgloss/libnosys/pthread_getconcurrency.c
libgloss/libnosys/pthread_getcpuclockid.c
libgloss/libnosys/pthread_getname_np.c
libgloss/libnosys/pthread_getschedparam.c
libgloss/libnosys/pthread_getspecific.c
libgloss/libnosys/pthread_join.c
libgloss/libnosys/pthread_key_create.c
libgloss/libnosys/pthread_key_delete.c
libgloss/libnosys/pthread_mutex_clocklock.c
libgloss/libnosys/pthread_mutex_destroy.c
libgloss/libnosys/pthread_mutex_getprioceiling.c
libgloss/libnosys/pthread_mutex_init.c
libgloss/libnosys/pthread_mutex_lock.c
libgloss/libnosys/pthread_mutex_setprioceiling.c
libgloss/libnosys/pthread_mutex_timedlock.c
libgloss/libnosys/pthread_mutex_trylock.c
libgloss/libnosys/pthread_mutex_unlock.c
libgloss/libnosys/pthread_mutexattr_destroy.c
libgloss/libnosys/pthread_mutexattr_getprioceiling.c
libgloss/libnosys/pthread_mutexattr_getprotocol.c
libgloss/libnosys/pthread_mutexattr_getpshared.c
libgloss/libnosys/pthread_mutexattr_gettype.c
libgloss/libnosys/pthread_mutexattr_init.c
libgloss/libnosys/pthread_mutexattr_setprioceiling.c
libgloss/libnosys/pthread_mutexattr_setprotocol.c
libgloss/libnosys/pthread_mutexattr_setpshared.c
libgloss/libnosys/pthread_mutexattr_settype.c
libgloss/libnosys/pthread_once.c
libgloss/libnosys/pthread_rwlock_clockrdlock.c
libgloss/libnosys/pthread_rwlock_clockwrlock.c
libgloss/libnosys/pthread_rwlock_destroy.c
libgloss/libnosys/pthread_rwlock_init.c
libgloss/libnosys/pthread_rwlock_rdlock.c
libgloss/libnosys/pthread_rwlock_timedrdlock.c
libgloss/libnosys/pthread_rwlock_timedwrlock.c
libgloss/libnosys/pthread_rwlock_tryrdlock.c
libgloss/libnosys/pthread_rwlock_trywrlock.c
libgloss/libnosys/pthread_rwlock_unlock.c
libgloss/libnosys/pthread_rwlock_wrlock.c
libgloss/libnosys/pthread_rwlockattr_destroy.c
libgloss/libnosys/pthread_rwlockattr_getpshared.c
libgloss/libnosys/pthread_rwlockattr_init.c
libgloss/libnosys/pthread_rwlockattr_setpshared.c
libgloss/libnosys/pthread_self.c
libgloss/libnosys/pthread_setaffinity_np.c
libgloss/libnosys/pthread_setcancelstate.c
libgloss/libnosys/pthread_setcanceltype.c
libgloss/libnosys/pthread_setconcurrency.c
libgloss/libnosys/pthread_setname_np.c
libgloss/libnosys/pthread_setschedparam.c
libgloss/libnosys/pthread_setschedprio.c
libgloss/libnosys/pthread_setspecific.c
libgloss/libnosys/pthread_spin_destroy.c
libgloss/libnosys/pthread_spin_init.c
libgloss/libnosys/pthread_spin_lock.c
libgloss/libnosys/pthread_spin_trylock.c
libgloss/libnosys/pthread_spin_unlock.c
libgloss/libnosys/pthread_testcancel.c
libgloss/libnosys/pthread_yield.c
libgloss/riscv/sys_access.c
libgloss/riscv/sys_chdir.c
libgloss/riscv/sys_chmod.c
libgloss/riscv/sys_chown.c
libgloss/riscv/sys_close.c
libgloss/riscv/sys_conv_stat.c
libgloss/riscv/sys_execve.c
libgloss/riscv/sys_faccessat.c
libgloss/riscv/sys_fork.c
libgloss/riscv/sys_fstat.c
libgloss/riscv/sys_fstatat.c
libgloss/riscv/sys_ftime.c
libgloss/riscv/sys_getcwd.c
libgloss/riscv/sys_getpid.c
libgloss/riscv/sys_getreent.c
libgloss/riscv/sys_gettimeofday.c
libgloss/riscv/sys_isatty.c
libgloss/riscv/sys_kill.c
libgloss/riscv/sys_link.c
libgloss/riscv/sys_lseek.c
libgloss/riscv/sys_lstat.c
libgloss/riscv/sys_open.c
libgloss/riscv/sys_openat.c
libgloss/riscv/sys_read.c
libgloss/riscv/sys_sbrk.c
libgloss/riscv/sys_stat.c
libgloss/riscv/sys_sysconf.c
libgloss/riscv/sys_times.c
libgloss/riscv/sys_unlink.c
libgloss/riscv/sys_utime.c
libgloss/riscv/sys_wait.c
libgloss/riscv/sys_write.c
libgloss/riscv/nanosleep.c
				`),
				CFlags: []string{
					"-DHAVE_CONFIG_H",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + libcDir,
					"-I" + filepath.Join(libcDir, "riscv"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					"-I" + filepath.Join(baseDir, "libgloss", "riscv"),
					"-I" + filepath.Join(baseDir, "libgloss", "riscv", "esp"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
			{
				OutputFileName: "libc-" + target + ".a",
				Files: joinFileList(libcDir, `
argz/argz_add.c
argz/argz_add_sep.c
argz/argz_append.c
argz/argz_count.c
argz/argz_create.c
argz/argz_create_sep.c
argz/argz_delete.c
argz/argz_extract.c
argz/argz_insert.c
argz/argz_next.c
argz/argz_replace.c
argz/argz_stringify.c
argz/buf_findstr.c
argz/envz_entry.c
argz/envz_get.c
argz/envz_add.c
argz/envz_remove.c
argz/envz_merge.c
argz/envz_strip.c
stdlib/__adjust.c
stdlib/__atexit.c
stdlib/__call_atexit.c
stdlib/__exp10.c
stdlib/__ten_mu.c
stdlib/_Exit.c
stdlib/abort.c
stdlib/abs.c
stdlib/aligned_alloc.c
stdlib/assert.c
stdlib/atexit.c
stdlib/atof.c
stdlib/atoff.c
stdlib/atoi.c
stdlib/atol.c
stdlib/calloc.c
stdlib/callocr.c
stdlib/cfreer.c
stdlib/div.c
stdlib/dtoa.c
stdlib/dtoastub.c
stdlib/environ.c
stdlib/envlock.c
stdlib/eprintf.c
stdlib/exit.c
stdlib/freer.c
stdlib/gdtoa-gethex.c
stdlib/gdtoa-hexnan.c
stdlib/getenv.c
stdlib/getenv_r.c
stdlib/imaxabs.c
stdlib/imaxdiv.c
stdlib/itoa.c
stdlib/labs.c
stdlib/ldiv.c
stdlib/ldtoa.c
stdlib/gdtoa-ldtoa.c
stdlib/gdtoa-gdtoa.c
stdlib/gdtoa-dmisc.c
stdlib/gdtoa-gmisc.c
stdlib/mallinfor.c
stdlib/malloc.c
stdlib/mallocr.c
stdlib/mallstatsr.c
stdlib/mblen.c
stdlib/mblen_r.c
stdlib/mbstowcs.c
stdlib/mbstowcs_r.c
stdlib/mbtowc.c
stdlib/mbtowc_r.c
stdlib/mlock.c
stdlib/mprec.c
stdlib/msizer.c
stdlib/mstats.c
stdlib/on_exit_args.c
stdlib/quick_exit.c
stdlib/rand.c
stdlib/rand_r.c
stdlib/random.c
stdlib/realloc.c
stdlib/reallocarray.c
stdlib/reallocf.c
stdlib/reallocr.c
stdlib/sb_charsets.c
stdlib/strtod.c
stdlib/strtoimax.c
stdlib/strtol.c
stdlib/strtoul.c
stdlib/strtoumax.c
stdlib/utoa.c
stdlib/wcstod.c
stdlib/wcstoimax.c
stdlib/wcstol.c
stdlib/wcstoul.c
stdlib/wcstoumax.c
stdlib/wcstombs.c
stdlib/wcstombs_r.c
stdlib/wctomb.c
stdlib/wctomb_r.c
stdlib/strtodg.c
stdlib/strtold.c
stdlib/strtorx.c
stdlib/wcstold.c
stdlib/arc4random.c
stdlib/arc4random_uniform.c
stdlib/cxa_atexit.c
stdlib/cxa_finalize.c
stdlib/drand48.c
stdlib/ecvtbuf.c
stdlib/efgcvt.c
stdlib/erand48.c
stdlib/jrand48.c
stdlib/lcong48.c
stdlib/lrand48.c
stdlib/mrand48.c
stdlib/msize.c
stdlib/mtrim.c
stdlib/nrand48.c
stdlib/rand48.c
stdlib/seed48.c
stdlib/srand48.c
stdlib/strtoll.c
stdlib/strtoll_r.c
stdlib/strtoull.c
stdlib/strtoull_r.c
stdlib/wcstoll.c
stdlib/wcstoll_r.c
stdlib/wcstoull.c
stdlib/wcstoull_r.c
stdlib/atoll.c
stdlib/llabs.c
stdlib/lldiv.c
stdlib/a64l.c
stdlib/btowc.c
stdlib/getopt.c
stdlib/getsubopt.c
stdlib/l64a.c
stdlib/malign.c
stdlib/malignr.c
stdlib/malloptr.c
stdlib/mbrlen.c
stdlib/mbrtowc.c
stdlib/mbsinit.c
stdlib/mbsnrtowcs.c
stdlib/mbsrtowcs.c
stdlib/on_exit.c
stdlib/pvallocr.c
stdlib/valloc.c
stdlib/vallocr.c
stdlib/wcrtomb.c
stdlib/wcsnrtombs.c
stdlib/wcsrtombs.c
stdlib/wctob.c
stdlib/putenv.c
stdlib/putenv_r.c
stdlib/setenv.c
stdlib/setenv_r.c
stdlib/rpmatch.c
stdlib/system.c
ctype/ctype_.c
ctype/isalnum.c
ctype/isalpha.c
ctype/iscntrl.c
ctype/isdigit.c
ctype/islower.c
ctype/isupper.c
ctype/isprint.c
ctype/ispunct.c
ctype/isspace.c
ctype/isxdigit.c
ctype/tolower.c
ctype/toupper.c
ctype/categories.c
ctype/isalnum_l.c
ctype/isalpha_l.c
ctype/isascii.c
ctype/isascii_l.c
ctype/isblank.c
ctype/isblank_l.c
ctype/iscntrl_l.c
ctype/isdigit_l.c
ctype/islower_l.c
ctype/isupper_l.c
ctype/isprint_l.c
ctype/ispunct_l.c
ctype/isspace_l.c
ctype/iswalnum.c
ctype/iswalnum_l.c
ctype/iswalpha.c
ctype/iswalpha_l.c
ctype/iswblank.c
ctype/iswblank_l.c
ctype/iswcntrl.c
ctype/iswcntrl_l.c
ctype/iswctype.c
ctype/iswctype_l.c
ctype/iswdigit.c
ctype/iswdigit_l.c
ctype/iswgraph.c
ctype/iswgraph_l.c
ctype/iswlower.c
ctype/iswlower_l.c
ctype/iswprint.c
ctype/iswprint_l.c
ctype/iswpunct.c
ctype/iswpunct_l.c
ctype/iswspace.c
ctype/iswspace_l.c
ctype/iswupper.c
ctype/iswupper_l.c
ctype/iswxdigit.c
ctype/iswxdigit_l.c
ctype/isxdigit_l.c
ctype/jp2uc.c
ctype/toascii.c
ctype/toascii_l.c
ctype/tolower_l.c
ctype/toupper_l.c
ctype/towctrans.c
ctype/towctrans_l.c
ctype/towlower.c
ctype/towlower_l.c
ctype/towupper.c
ctype/towupper_l.c
ctype/wctrans.c
ctype/wctrans_l.c
ctype/wctype.c
ctype/wctype_l.c
search/bsearch.c
search/ndbm.c
search/qsort.c
search/hash.c
search/hash_bigkey.c
search/hash_buf.c
search/hash_func.c
search/hash_log2.c
search/hash_page.c
search/hcreate.c
search/hcreate_r.c
search/tdelete.c
search/tdestroy.c
search/tfind.c
search/tsearch.c
search/twalk.c
search/bsd_qsort_r.c
search/qsort_r.c
stdio/nano-vfprintf_float.c
stdio/nano-svfprintf.c
stdio/nano-svfscanf.c
stdio/nano-vfprintf.c
stdio/nano-vfprintf_i.c
stdio/nano-vfscanf.c
stdio/nano-vfscanf_i.c
stdio/nano-vfscanf_float.c
stdio/clearerr.c
stdio/fclose.c
stdio/fdopen.c
stdio/feof.c
stdio/ferror.c
stdio/fflush.c
stdio/fgetc.c
stdio/fgetpos.c
stdio/fgets.c
stdio/fileno.c
stdio/findfp.c
stdio/flags.c
stdio/fopen.c
stdio/fprintf.c
stdio/fputc.c
stdio/fputs.c
stdio/fread.c
stdio/freopen.c
stdio/fscanf.c
stdio/fseek.c
stdio/fsetpos.c
stdio/ftell.c
stdio/fvwrite.c
stdio/fwalk.c
stdio/fwrite.c
stdio/getc.c
stdio/getchar.c
stdio/getc_u.c
stdio/getchar_u.c
stdio/getdelim.c
stdio/getline.c
stdio/gets.c
stdio/makebuf.c
stdio/perror.c
stdio/printf.c
stdio/putc.c
stdio/putchar.c
stdio/putc_u.c
stdio/putchar_u.c
stdio/puts.c
stdio/refill.c
stdio/remove.c
stdio/rename.c
stdio/rewind.c
stdio/rget.c
stdio/scanf.c
stdio/sccl.c
stdio/setbuf.c
stdio/setbuffer.c
stdio/setlinebuf.c
stdio/setvbuf.c
stdio/snprintf.c
stdio/sprintf.c
stdio/sscanf.c
stdio/stdio.c
stdio/svfiwprintf.c
stdio/svfiwscanf.c
stdio/svfwprintf.c
stdio/svfwscanf.c
stdio/tmpfile.c
stdio/tmpnam.c
stdio/ungetc.c
stdio/vdprintf.c
stdio/vfiwprintf.c
stdio/vfiwscanf.c
stdio/vfwscanf.c
stdio/vprintf.c
stdio/vscanf.c
stdio/vsnprintf.c
stdio/vsprintf.c
stdio/vsscanf.c
stdio/wbuf.c
stdio/wsetup.c
stdio/asprintf.c
stdio/fcloseall.c
stdio/fseeko.c
stdio/ftello.c
stdio/getw.c
stdio/mktemp.c
stdio/putw.c
stdio/vasprintf.c
stdio/asnprintf.c
stdio/clearerr_u.c
stdio/dprintf.c
stdio/feof_u.c
stdio/ferror_u.c
stdio/fflush_u.c
stdio/fgetc_u.c
stdio/fgets_u.c
stdio/fgetwc.c
stdio/fgetwc_u.c
stdio/fgetws.c
stdio/fgetws_u.c
stdio/fileno_u.c
stdio/fmemopen.c
stdio/fopencookie.c
stdio/fpurge.c
stdio/fputc_u.c
stdio/fputs_u.c
stdio/fputwc.c
stdio/fputwc_u.c
stdio/fputws.c
stdio/fputws_u.c
stdio/fread_u.c
stdio/fsetlocking.c
stdio/funopen.c
stdio/fwide.c
stdio/fwprintf.c
stdio/fwrite_u.c
stdio/fwscanf.c
stdio/getwc.c
stdio/getwc_u.c
stdio/getwchar.c
stdio/getwchar_u.c
stdio/open_memstream.c
stdio/putwc.c
stdio/putwc_u.c
stdio/putwchar.c
stdio/putwchar_u.c
stdio/stdio_ext.c
stdio/swprintf.c
stdio/swscanf.c
stdio/ungetwc.c
stdio/vasnprintf.c
stdio/vswprintf.c
stdio/vswscanf.c
stdio/vwprintf.c
stdio/vwscanf.c
stdio/wprintf.c
stdio/wscanf.c
string/bcopy.c
string/bzero.c
string/explicit_bzero.c
string/ffsl.c
string/ffsll.c
string/fls.c
string/flsl.c
string/flsll.c
string/index.c
string/memchr.c
string/memcmp.c
string/memcpy.c
string/memmove.c
string/memset.c
string/rindex.c
string/strcasecmp.c
string/strcat.c
string/strchr.c
string/strcmp.c
string/strcoll.c
string/strcpy.c
string/strcspn.c
string/strdup.c
string/strdup_r.c
string/strerror.c
string/strerror_r.c
string/strlcat.c
string/strlcpy.c
string/strlen.c
string/strlwr.c
string/strncasecmp.c
string/strncat.c
string/strncmp.c
string/strncpy.c
string/strnlen.c
string/strnstr.c
string/strpbrk.c
string/strrchr.c
string/strsep.c
string/strsignal.c
string/strspn.c
string/strtok.c
string/strtok_r.c
string/strupr.c
string/strxfrm.c
string/strstr.c
string/swab.c
string/timingsafe_bcmp.c
string/timingsafe_memcmp.c
string/u_strerr.c
string/wcscat.c
string/wcschr.c
string/wcscmp.c
string/wcscoll.c
string/wcscpy.c
string/wcscspn.c
string/wcslcat.c
string/wcslcpy.c
string/wcslen.c
string/wcsncat.c
string/wcsncmp.c
string/wcsncpy.c
string/wcsnlen.c
string/wcspbrk.c
string/wcsrchr.c
string/wcsspn.c
string/wcsstr.c
string/wcstok.c
string/wcswidth.c
string/wcsxfrm.c
string/wcwidth.c
string/wmemchr.c
string/wmemcmp.c
string/wmemcpy.c
string/wmemmove.c
string/wmemset.c
string/xpg_strerror_r.c
string/bcmp.c
string/memccpy.c
string/mempcpy.c
string/stpcpy.c
string/stpncpy.c
string/strndup.c
string/strcasestr.c
string/strchrnul.c
string/strndup_r.c
string/wcpcpy.c
string/wcpncpy.c
string/wcsdup.c
string/gnu_basename.c
string/memmem.c
string/memrchr.c
string/rawmemchr.c
string/strcasecmp_l.c
string/strcoll_l.c
string/strncasecmp_l.c
string/strverscmp.c
string/strxfrm_l.c
string/wcscasecmp.c
string/wcscasecmp_l.c
string/wcscoll_l.c
string/wcsncasecmp.c
string/wcsncasecmp_l.c
string/wcsxfrm_l.c
string/wmempcpy.c
signal/psignal.c
signal/raise.c
signal/signal.c
signal/sig2str.c
time/asctime.c
time/asctime_r.c
time/clock.c
time/ctime.c
time/ctime_r.c
time/difftime.c
time/gettzinfo.c
time/gmtime.c
time/gmtime_r.c
time/lcltime.c
time/lcltime_r.c
time/mktime.c
time/month_lengths.c
time/strftime.c
time/strptime.c
time/time.c
time/tzcalc_limits.c
time/tzlock.c
time/tzset.c
time/tzset_r.c
time/tzvars.c
time/wcsftime.c
locale/locale.c
locale/localeconv.c
locale/duplocale.c
locale/freelocale.c
locale/lctype.c
locale/lmessages.c
locale/lnumeric.c
locale/lmonetary.c
locale/newlocale.c
locale/nl_langinfo.c
locale/timelocal.c
locale/uselocale.c
reent/closer.c
reent/reent.c
reent/impure.c
reent/fcntlr.c
reent/fstatr.c
reent/getentropyr.c
reent/getreent.c
reent/gettimeofdayr.c
reent/isattyr.c
reent/linkr.c
reent/lseekr.c
reent/mkdirr.c
reent/openr.c
reent/readr.c
reent/renamer.c
reent/signalr.c
reent/signgam.c
reent/sbrkr.c
reent/statr.c
reent/timesr.c
reent/unlinkr.c
reent/writer.c
reent/execr.c
errno/errno.c
misc/__dprintf.c
misc/unctrl.c
misc/ffs.c
misc/init.c
misc/fini.c
misc/lock.c
posix/closedir.c
posix/collate.c
posix/collcmp.c
posix/creat.c
posix/dirfd.c
posix/glob.c
posix/_isatty.c
posix/isatty.c
posix/opendir.c
posix/readdir.c
posix/readdir_r.c
posix/regcomp.c
posix/regerror.c
posix/regexec.c
posix/regfree.c
posix/rewinddir.c
posix/sleep.c
posix/usleep.c
posix/telldir.c
posix/ftw.c
posix/nftw.c
posix/scandir.c
posix/seekdir.c
posix/execl.c
posix/execle.c
posix/execlp.c
posix/execv.c
posix/execve.c
posix/execvp.c
posix/wordexp.c
posix/wordfree.c
posix/popen.c
posix/posix_spawn.c
syscalls/sysclose.c
syscalls/sysfcntl.c
syscalls/sysfstat.c
syscalls/sysgetentropy.c
syscalls/sysgetpid.c
syscalls/sysgettod.c
syscalls/sysisatty.c
syscalls/syskill.c
syscalls/syslink.c
syscalls/syslseek.c
syscalls/sysopen.c
syscalls/sysread.c
syscalls/syssbrk.c
syscalls/sysstat.c
syscalls/systimes.c
syscalls/sysunlink.c
syscalls/syswrite.c
syscalls/sysexecve.c
syscalls/sysfork.c
syscalls/syswait.c
iconv/ces/utf-8.c
iconv/ces/utf-16.c
iconv/ces/ucs-2.c
iconv/ces/us-ascii.c
iconv/ces/ucs-4.c
iconv/ces/ucs-2-internal.c
iconv/ces/ucs-4-internal.c
iconv/ces/cesbi.c
iconv/ces/table.c
iconv/ces/table-pcs.c
iconv/ces/euc.c
iconv/ccs/ccsbi.c
iconv/ccs/iso_8859_10.c
iconv/ccs/iso_8859_13.c
iconv/ccs/iso_8859_14.c
iconv/ccs/iso_8859_15.c
iconv/ccs/iso_8859_1.c
iconv/ccs/iso_8859_2.c
iconv/ccs/iso_8859_3.c
iconv/ccs/iso_8859_4.c
iconv/ccs/iso_8859_5.c
iconv/ccs/iso_8859_6.c
iconv/ccs/iso_8859_7.c
iconv/ccs/iso_8859_8.c
iconv/ccs/iso_8859_9.c
iconv/ccs/iso_8859_11.c
iconv/ccs/win_1250.c
iconv/ccs/win_1252.c
iconv/ccs/win_1254.c
iconv/ccs/win_1256.c
iconv/ccs/win_1258.c
iconv/ccs/win_1251.c
iconv/ccs/win_1253.c
iconv/ccs/win_1255.c
iconv/ccs/win_1257.c
iconv/ccs/koi8_r.c
iconv/ccs/koi8_u.c
iconv/ccs/koi8_ru.c
iconv/ccs/koi8_uni.c
iconv/ccs/iso_ir_111.c
iconv/ccs/big5.c
iconv/ccs/cp775.c
iconv/ccs/cp850.c
iconv/ccs/cp852.c
iconv/ccs/cp855.c
iconv/ccs/cp866.c
iconv/ccs/jis_x0212_1990.c
iconv/ccs/jis_x0201_1976.c
iconv/ccs/jis_x0208_1990.c
iconv/ccs/ksx1001.c
iconv/ccs/cns11643_plane1.c
iconv/ccs/cns11643_plane2.c
iconv/ccs/cns11643_plane14.c
iconv/lib/aliasesi.c
iconv/lib/ucsconv.c
iconv/lib/nullconv.c
iconv/lib/iconv.c
iconv/lib/aliasesbi.c
iconv/lib/iconvnls.c
ssp/chk_fail.c
ssp/stack_protector.c
ssp/memcpy_chk.c
ssp/memmove_chk.c
ssp/mempcpy_chk.c
ssp/memset_chk.c
ssp/stpcpy_chk.c
ssp/stpncpy_chk.c
ssp/strcat_chk.c
ssp/strcpy_chk.c
ssp/strncat_chk.c
ssp/strncpy_chk.c
ssp/gets_chk.c
ssp/snprintf_chk.c
ssp/sprintf_chk.c
ssp/vsnprintf_chk.c
ssp/vsprintf_chk.c
machine/riscv/memmove.S
machine/riscv/memmove-stub.c
machine/riscv/memset.S
machine/riscv/memcpy-asm.S
machine/riscv/memcpy.c
machine/riscv/strlen.c
machine/riscv/strcpy.c
machine/riscv/strcmp.S
machine/riscv/setjmp.S
machine/riscv/ieeefp.c
machine/riscv/ffs.c
				`),
				CFlags: []string{
					"-DHAVE_CONFIG_H",
					"-D_LIBC",
					"-DHAVE_NANOSLEEP",
					"-D__NO_SYSCALLS__",
					"-D_NO_GLOB",
					"-D_NO_EXECVE",
					"-D_NO_GETLOGIN",
					"-D_NO_GETPWENT",
					"-D_NO_GETUT",
					"-D_NO_GETPASS",
					"-D_NO_SIGSET",
					"-D_NO_WORDEXP",
					"-D_NO_POPEN",
					"-D_NO_POSIX_SPAWN",
					"-DHAVE_FCNTL",
					"-DHAVE_BLKSIZE",
					"-DHAVE_OPENDIR",
					"-DHAVE_RENAME",
					"-DGETREENT_PROVIDED",
					"-DSIGNAL_PROVIDED",
					"-D__ESP__",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + filepath.Join(baseDir, "newlib"),
					"-I" + libcDir,
					"-I" + filepath.Join(libcDir, "riscv"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					// TODO(MeteorsLiu): support riscv
					"-idirafter" + filepath.Join(baseDir, "include"),
					"-I" + filepath.Join(libcDir, "ssp"),
					"-I" + filepath.Join(libcDir, "locale"),
					"-I" + filepath.Join(libcDir, "errno"),
					"-I" + filepath.Join(libcDir, "syscalls"),
					"-I" + filepath.Join(libcDir, "iconv", "lib"),
					"-I" + filepath.Join(libcDir, "argz"),
					"-I" + filepath.Join(libcDir, "stdio"),
					"-I" + filepath.Join(libcDir, "iconv", "ces"),
					"-I" + filepath.Join(libcDir, "iconv", "ccs"),
					"-I" + filepath.Join(libcDir, "ctype"),
					"-I" + filepath.Join(libcDir, "signal"),
					"-I" + filepath.Join(libcDir, "time"),
					"-I" + filepath.Join(libcDir, "reent"),
					"-I" + filepath.Join(libcDir, "machine", "riscv", "include"),
					"-I" + filepath.Join(libcDir, "string"),
					"-I" + filepath.Join(libcDir, "iconv", "ces"),
					"-I" + filepath.Join(libcDir, "search"),
					"-I" + filepath.Join(libcDir, "misc"),
					"-I" + filepath.Join(libcDir, "posix"),
					"-I" + filepath.Join(libcDir, "stdlib"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: withDefaultCCFlags([]string{
					"-fno-builtin",
					"-Wno-implicit-function-declaration",
					"-Wno-int-conversion",
					"-Wno-unused-command-line-argument",
				}),
			},
			{
				OutputFileName: "libm-fbuiltin_fno_math_errno-" + target + ".a",
				Files: joinFileList(baseDir, `
newlib/libm/common/acoshl.c
newlib/libm/common/acosl.c
newlib/libm/common/asinhl.c
newlib/libm/common/asinl.c
newlib/libm/common/atan2l.c
newlib/libm/common/atanhl.c
newlib/libm/common/atanl.c
newlib/libm/common/cbrtl.c
newlib/libm/common/ceill.c
newlib/libm/common/copysignl.c
newlib/libm/common/cosf.c
newlib/libm/common/coshl.c
newlib/libm/common/cosl.c
newlib/libm/common/erfcl.c
newlib/libm/common/erfl.c
newlib/libm/common/exp.c
newlib/libm/common/exp2.c
newlib/libm/common/exp2l.c
newlib/libm/common/exp_data.c
newlib/libm/common/expl.c
newlib/libm/common/expm1l.c
newlib/libm/common/fabsl.c
newlib/libm/common/fdiml.c
newlib/libm/common/floorl.c
newlib/libm/common/fmal.c
newlib/libm/common/fmaxl.c
newlib/libm/common/fminl.c
newlib/libm/common/fmodl.c
newlib/libm/common/frexpl.c
newlib/libm/common/hypotl.c
newlib/libm/common/ilogbl.c
newlib/libm/common/ldexpl.c
newlib/libm/common/lgammal.c
newlib/libm/common/llrintl.c
newlib/libm/common/llroundl.c
newlib/libm/common/log.c
newlib/libm/common/log10l.c
newlib/libm/common/log1pl.c
newlib/libm/common/log2.c
newlib/libm/common/log2_data.c
newlib/libm/common/log2l.c
newlib/libm/common/log_data.c
newlib/libm/common/logbl.c
newlib/libm/common/logl.c
newlib/libm/common/lrintl.c
newlib/libm/common/lroundl.c
newlib/libm/common/math_err.c
newlib/libm/common/math_errf.c
newlib/libm/common/modfl.c
newlib/libm/common/nanl.c
newlib/libm/common/nearbyintl.c
newlib/libm/common/nextafterl.c
newlib/libm/common/nexttoward.c
newlib/libm/common/nexttowardf.c
newlib/libm/common/nexttowardl.c
newlib/libm/common/pow.c
newlib/libm/common/pow_log_data.c
newlib/libm/common/powl.c
newlib/libm/common/remainderl.c
newlib/libm/common/remquol.c
newlib/libm/common/rintl.c
newlib/libm/common/roundl.c
newlib/libm/common/s_cbrt.c
newlib/libm/common/s_copysign.c
newlib/libm/common/s_exp10.c
newlib/libm/common/s_expm1.c
newlib/libm/common/s_fdim.c
newlib/libm/common/s_finite.c
newlib/libm/common/s_fma.c
newlib/libm/common/s_fmax.c
newlib/libm/common/s_fmin.c
newlib/libm/common/s_fpclassify.c
newlib/libm/common/s_ilogb.c
newlib/libm/common/s_infinity.c
newlib/libm/common/s_isinf.c
newlib/libm/common/s_isinfd.c
newlib/libm/common/s_isnan.c
newlib/libm/common/s_isnand.c
newlib/libm/common/s_llrint.c
newlib/libm/common/s_llround.c
newlib/libm/common/s_log1p.c
newlib/libm/common/s_log2.c
newlib/libm/common/s_logb.c
newlib/libm/common/s_lrint.c
newlib/libm/common/s_lround.c
newlib/libm/common/s_modf.c
newlib/libm/common/s_nan.c
newlib/libm/common/s_nearbyint.c
newlib/libm/common/s_nextafter.c
newlib/libm/common/s_pow10.c
newlib/libm/common/s_remquo.c
newlib/libm/common/s_rint.c
newlib/libm/common/s_round.c
newlib/libm/common/s_scalbln.c
newlib/libm/common/s_scalbn.c
newlib/libm/common/s_signbit.c
newlib/libm/common/s_trunc.c
newlib/libm/common/scalblnl.c
newlib/libm/common/scalbnl.c
newlib/libm/common/sf_cbrt.c
newlib/libm/common/sf_copysign.c
newlib/libm/common/sf_exp.c
newlib/libm/common/sf_exp10.c
newlib/libm/common/sf_exp2.c
newlib/libm/common/sf_exp2_data.c
newlib/libm/common/sf_expm1.c
newlib/libm/common/sf_fdim.c
newlib/libm/common/sf_finite.c
newlib/libm/common/sf_fma.c
newlib/libm/common/sf_fmax.c
newlib/libm/common/sf_fmin.c
newlib/libm/common/sf_fpclassify.c
newlib/libm/common/sf_ilogb.c
newlib/libm/common/sf_infinity.c
newlib/libm/common/sf_isinf.c
newlib/libm/common/sf_isinff.c
newlib/libm/common/sf_isnan.c
newlib/libm/common/sf_isnanf.c
newlib/libm/common/sf_llrint.c
newlib/libm/common/sf_llround.c
newlib/libm/common/sf_log.c
newlib/libm/common/sf_log1p.c
newlib/libm/common/sf_log2.c
newlib/libm/common/sf_log2_data.c
newlib/libm/common/sf_log_data.c
newlib/libm/common/sf_logb.c
newlib/libm/common/sf_lrint.c
newlib/libm/common/sf_lround.c
newlib/libm/common/sf_modf.c
newlib/libm/common/sf_nan.c
newlib/libm/common/sf_nearbyint.c
newlib/libm/common/sf_nextafter.c
newlib/libm/common/sf_pow.c
newlib/libm/common/sf_pow10.c
newlib/libm/common/sf_pow_log2_data.c
newlib/libm/common/sf_remquo.c
newlib/libm/common/sf_rint.c
newlib/libm/common/sf_round.c
newlib/libm/common/sf_scalbln.c
newlib/libm/common/sf_scalbn.c
newlib/libm/common/sf_trunc.c
newlib/libm/common/sincosf.c
newlib/libm/common/sincosf_data.c
newlib/libm/common/sinf.c
newlib/libm/common/sinhl.c
newlib/libm/common/sinl.c
newlib/libm/common/sl_finite.c
newlib/libm/common/sqrtl.c
newlib/libm/common/tanhl.c
newlib/libm/common/tanl.c
newlib/libm/common/tgammal.c
newlib/libm/common/truncl.c
				`),
				CFlags: append(
					append([]string{}, libmCommonCFlags...),
					"-fbuiltin",
					"-fno-math-errno",
				),
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
			{
				OutputFileName: "libm-default-" + target + ".a",
				Files: joinFileList(baseDir, `
newlib/libm/complex/cabs.c
newlib/libm/complex/cabsf.c
newlib/libm/complex/cabsl.c
newlib/libm/complex/cacos.c
newlib/libm/complex/cacosf.c
newlib/libm/complex/cacosh.c
newlib/libm/complex/cacoshf.c
newlib/libm/complex/cacoshl.c
newlib/libm/complex/cacosl.c
newlib/libm/complex/carg.c
newlib/libm/complex/cargf.c
newlib/libm/complex/cargl.c
newlib/libm/complex/casin.c
newlib/libm/complex/casinf.c
newlib/libm/complex/casinh.c
newlib/libm/complex/casinhf.c
newlib/libm/complex/casinhl.c
newlib/libm/complex/casinl.c
newlib/libm/complex/catan.c
newlib/libm/complex/catanf.c
newlib/libm/complex/catanh.c
newlib/libm/complex/catanhf.c
newlib/libm/complex/catanhl.c
newlib/libm/complex/catanl.c
newlib/libm/complex/ccos.c
newlib/libm/complex/ccosf.c
newlib/libm/complex/ccosh.c
newlib/libm/complex/ccoshf.c
newlib/libm/complex/ccoshl.c
newlib/libm/complex/ccosl.c
newlib/libm/complex/cephes_subr.c
newlib/libm/complex/cephes_subrf.c
newlib/libm/complex/cephes_subrl.c
newlib/libm/complex/cexp.c
newlib/libm/complex/cexpf.c
newlib/libm/complex/cexpl.c
newlib/libm/complex/cimag.c
newlib/libm/complex/cimagf.c
newlib/libm/complex/cimagl.c
newlib/libm/complex/clog.c
newlib/libm/complex/clog10.c
newlib/libm/complex/clog10f.c
newlib/libm/complex/clogf.c
newlib/libm/complex/clogl.c
newlib/libm/complex/conj.c
newlib/libm/complex/conjf.c
newlib/libm/complex/conjl.c
newlib/libm/complex/cpow.c
newlib/libm/complex/cpowf.c
newlib/libm/complex/cpowl.c
newlib/libm/complex/cproj.c
newlib/libm/complex/cprojf.c
newlib/libm/complex/cprojl.c
newlib/libm/complex/creal.c
newlib/libm/complex/crealf.c
newlib/libm/complex/creall.c
newlib/libm/complex/csin.c
newlib/libm/complex/csinf.c
newlib/libm/complex/csinh.c
newlib/libm/complex/csinhf.c
newlib/libm/complex/csinhl.c
newlib/libm/complex/csinl.c
newlib/libm/complex/csqrt.c
newlib/libm/complex/csqrtf.c
newlib/libm/complex/csqrtl.c
newlib/libm/complex/ctan.c
newlib/libm/complex/ctanf.c
newlib/libm/complex/ctanh.c
newlib/libm/complex/ctanhf.c
newlib/libm/complex/ctanhl.c
newlib/libm/complex/ctanl.c
newlib/libm/fenv/fe_dfl_env.c
newlib/libm/fenv/feclearexcept.c
newlib/libm/fenv/fegetenv.c
newlib/libm/fenv/fegetexceptflag.c
newlib/libm/fenv/fegetround.c
newlib/libm/fenv/feholdexcept.c
newlib/libm/fenv/feraiseexcept.c
newlib/libm/fenv/fesetenv.c
newlib/libm/fenv/fesetexceptflag.c
newlib/libm/fenv/fesetround.c
newlib/libm/fenv/fetestexcept.c
newlib/libm/fenv/feupdateenv.c
newlib/libm/machine/riscv/e_sqrt.c
newlib/libm/machine/riscv/ef_sqrt.c
newlib/libm/machine/riscv/fe_dfl_env.c
newlib/libm/machine/riscv/feclearexcept.c
newlib/libm/machine/riscv/fegetenv.c
newlib/libm/machine/riscv/fegetexceptflag.c
newlib/libm/machine/riscv/fegetround.c
newlib/libm/machine/riscv/feholdexcept.c
newlib/libm/machine/riscv/feraiseexcept.c
newlib/libm/machine/riscv/fesetenv.c
newlib/libm/machine/riscv/fesetexceptflag.c
newlib/libm/machine/riscv/fesetround.c
newlib/libm/machine/riscv/fetestexcept.c
newlib/libm/machine/riscv/feupdateenv.c
newlib/libm/machine/riscv/s_copysign.c
newlib/libm/machine/riscv/s_fabs.c
newlib/libm/machine/riscv/s_finite.c
newlib/libm/machine/riscv/s_fma.c
newlib/libm/machine/riscv/s_fmax.c
newlib/libm/machine/riscv/s_fmin.c
newlib/libm/machine/riscv/s_fpclassify.c
newlib/libm/machine/riscv/s_isinf.c
newlib/libm/machine/riscv/s_isnan.c
newlib/libm/machine/riscv/s_llrint.c
newlib/libm/machine/riscv/s_llround.c
newlib/libm/machine/riscv/s_lrint.c
newlib/libm/machine/riscv/s_lround.c
newlib/libm/machine/riscv/sf_copysign.c
newlib/libm/machine/riscv/sf_fabs.c
newlib/libm/machine/riscv/sf_finite.c
newlib/libm/machine/riscv/sf_fma.c
newlib/libm/machine/riscv/sf_fmax.c
newlib/libm/machine/riscv/sf_fmin.c
newlib/libm/machine/riscv/sf_fpclassify.c
newlib/libm/machine/riscv/sf_isinf.c
newlib/libm/machine/riscv/sf_isnan.c
newlib/libm/machine/riscv/sf_llrint.c
newlib/libm/machine/riscv/sf_llround.c
newlib/libm/machine/riscv/sf_lrint.c
newlib/libm/machine/riscv/sf_lround.c
newlib/libm/math/e_acos.c
newlib/libm/math/e_acosh.c
newlib/libm/math/e_asin.c
newlib/libm/math/e_atan2.c
newlib/libm/math/e_atanh.c
newlib/libm/math/e_cosh.c
newlib/libm/math/e_exp.c
newlib/libm/math/e_fmod.c
newlib/libm/math/e_hypot.c
newlib/libm/math/e_j0.c
newlib/libm/math/e_j1.c
newlib/libm/math/e_jn.c
newlib/libm/math/e_log.c
newlib/libm/math/e_log10.c
newlib/libm/math/e_pow.c
newlib/libm/math/e_rem_pio2.c
newlib/libm/math/e_remainder.c
newlib/libm/math/e_scalb.c
newlib/libm/math/e_sinh.c
newlib/libm/math/e_sqrt.c
newlib/libm/math/e_tgamma.c
newlib/libm/math/ef_acos.c
newlib/libm/math/ef_acosh.c
newlib/libm/math/ef_asin.c
newlib/libm/math/ef_atan2.c
newlib/libm/math/ef_atanh.c
newlib/libm/math/ef_cosh.c
newlib/libm/math/ef_exp.c
newlib/libm/math/ef_fmod.c
newlib/libm/math/ef_hypot.c
newlib/libm/math/ef_j0.c
newlib/libm/math/ef_j1.c
newlib/libm/math/ef_jn.c
newlib/libm/math/ef_log.c
newlib/libm/math/ef_log10.c
newlib/libm/math/ef_pow.c
newlib/libm/math/ef_rem_pio2.c
newlib/libm/math/ef_remainder.c
newlib/libm/math/ef_scalb.c
newlib/libm/math/ef_sinh.c
newlib/libm/math/ef_sqrt.c
newlib/libm/math/ef_tgamma.c
newlib/libm/math/el_hypot.c
newlib/libm/math/er_lgamma.c
newlib/libm/math/erf_lgamma.c
newlib/libm/math/k_cos.c
newlib/libm/math/k_rem_pio2.c
newlib/libm/math/k_sin.c
newlib/libm/math/k_standard.c
newlib/libm/math/k_tan.c
newlib/libm/math/kf_cos.c
newlib/libm/math/kf_rem_pio2.c
newlib/libm/math/kf_sin.c
newlib/libm/math/kf_tan.c
newlib/libm/math/s_asinh.c
newlib/libm/math/s_atan.c
newlib/libm/math/s_ceil.c
newlib/libm/math/s_cos.c
newlib/libm/math/s_erf.c
newlib/libm/math/s_fabs.c
newlib/libm/math/s_floor.c
newlib/libm/math/s_frexp.c
newlib/libm/math/s_ldexp.c
newlib/libm/math/s_signif.c
newlib/libm/math/s_sin.c
newlib/libm/math/s_tan.c
newlib/libm/math/s_tanh.c
newlib/libm/math/sf_asinh.c
newlib/libm/math/sf_atan.c
newlib/libm/math/sf_ceil.c
newlib/libm/math/sf_cos.c
newlib/libm/math/sf_erf.c
newlib/libm/math/sf_fabs.c
newlib/libm/math/sf_floor.c
newlib/libm/math/sf_frexp.c
newlib/libm/math/sf_ldexp.c
newlib/libm/math/sf_signif.c
newlib/libm/math/sf_sin.c
newlib/libm/math/sf_tan.c
newlib/libm/math/sf_tanh.c
newlib/libm/math/w_acos.c
newlib/libm/math/w_acosh.c
newlib/libm/math/w_asin.c
newlib/libm/math/w_atan2.c
newlib/libm/math/w_atanh.c
newlib/libm/math/w_cosh.c
newlib/libm/math/w_drem.c
newlib/libm/math/w_exp.c
newlib/libm/math/w_exp2.c
newlib/libm/math/w_fmod.c
newlib/libm/math/w_gamma.c
newlib/libm/math/w_hypot.c
newlib/libm/math/w_j0.c
newlib/libm/math/w_j1.c
newlib/libm/math/w_jn.c
newlib/libm/math/w_lgamma.c
newlib/libm/math/w_log.c
newlib/libm/math/w_log10.c
newlib/libm/math/w_pow.c
newlib/libm/math/w_remainder.c
newlib/libm/math/w_scalb.c
newlib/libm/math/w_sincos.c
newlib/libm/math/w_sinh.c
newlib/libm/math/w_sqrt.c
newlib/libm/math/w_tgamma.c
newlib/libm/math/wf_acos.c
newlib/libm/math/wf_acosh.c
newlib/libm/math/wf_asin.c
newlib/libm/math/wf_atan2.c
newlib/libm/math/wf_atanh.c
newlib/libm/math/wf_cosh.c
newlib/libm/math/wf_drem.c
newlib/libm/math/wf_exp.c
newlib/libm/math/wf_exp2.c
newlib/libm/math/wf_fmod.c
newlib/libm/math/wf_gamma.c
newlib/libm/math/wf_hypot.c
newlib/libm/math/wf_j0.c
newlib/libm/math/wf_j1.c
newlib/libm/math/wf_jn.c
newlib/libm/math/wf_lgamma.c
newlib/libm/math/wf_log.c
newlib/libm/math/wf_log10.c
newlib/libm/math/wf_log2.c
newlib/libm/math/wf_pow.c
newlib/libm/math/wf_remainder.c
newlib/libm/math/wf_scalb.c
newlib/libm/math/wf_sincos.c
newlib/libm/math/wf_sinh.c
newlib/libm/math/wf_sqrt.c
newlib/libm/math/wf_tgamma.c
newlib/libm/math/wr_gamma.c
newlib/libm/math/wr_lgamma.c
newlib/libm/math/wrf_gamma.c
newlib/libm/math/wrf_lgamma.c
				`),
				CFlags:  append([]string{}, libmCommonCFlags...),
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
		},
	}
}

func getNewlibESP32ConfigXtensa(baseDir, target string) compile.CompileConfig {
	libcDir := filepath.Join(baseDir, "newlib", "libc")

	libcIncludeDir := []string{
		"-I" + filepath.Join(libcDir, "include"),
		"-I" + filepath.Join(baseDir, "newlib"),
		"-I" + libcDir,
	}

	return compile.CompileConfig{
		ExportCFlags: libcIncludeDir,
		Groups: []compile.CompileGroup{
			{
				OutputFileName: "libcrt0-" + target + ".a",
				Files: joinFileList(baseDir, `
libgloss/xtensa/clibrary_init.c
libgloss/xtensa/syscalls.c
libgloss/xtensa/sim-call.S
libgloss/xtensa/boards/esp32/board.c
libgloss/xtensa/crt1-boards.S
libgloss/xtensa/sleep.S
libgloss/xtensa/window-vectors.S
				`),
				CFlags: []string{
					"-DHAVE_CONFIG_H",
					"-D_LIBGLOSS",
					"-DQEMU_SEMIHOSTING_EXIT_ONLY",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					// TODO(MeteorsLiu): support riscv
					"-I" + filepath.Join(baseDir, "libgloss", "xtensa", "include"),
					"-I" + filepath.Join(baseDir, "libgloss", "xtensa", "boards", "esp32", "include"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
			{
				OutputFileName: "libgloss-" + target + ".a",
				Files: joinFileList(baseDir, `
libgloss/libnosys/chown.c
libgloss/libnosys/close.c
libgloss/libnosys/environ.c
libgloss/libnosys/errno.c
libgloss/libnosys/execve.c
libgloss/libnosys/fork.c
libgloss/libnosys/fstat.c
libgloss/libnosys/getpid.c
libgloss/libnosys/gettod.c
libgloss/libnosys/isatty.c
libgloss/libnosys/kill.c
libgloss/libnosys/link.c
libgloss/libnosys/lseek.c
libgloss/libnosys/open.c
libgloss/libnosys/read.c
libgloss/libnosys/readlink.c
libgloss/libnosys/sbrk.c
libgloss/libnosys/stat.c
libgloss/libnosys/symlink.c
libgloss/libnosys/times.c
libgloss/libnosys/unlink.c
libgloss/libnosys/wait.c
libgloss/libnosys/write.c
libgloss/libnosys/getentropy.c
libgloss/libnosys/_exit.c
libgloss/libnosys/getreent.c
libgloss/libnosys/time.c
libgloss/libnosys/fcntl.c
libgloss/libnosys/chdir.c
libgloss/libnosys/chmod.c
libgloss/libnosys/closedir.c
libgloss/libnosys/dirfd.c
libgloss/libnosys/ftw.c
libgloss/libnosys/getcwd.c
libgloss/libnosys/mkdir.c
libgloss/libnosys/nftw.c
libgloss/libnosys/opendir.c
libgloss/libnosys/pathconf.c
libgloss/libnosys/readdir.c
libgloss/libnosys/rewinddir.c
libgloss/libnosys/scandir.c
libgloss/libnosys/seekdir.c
libgloss/libnosys/telldir.c
libgloss/libnosys/rename.c
libgloss/libnosys/_pthread_cleanup_pop.c
libgloss/libnosys/_pthread_cleanup_pop_restore.c
libgloss/libnosys/_pthread_cleanup_push.c
libgloss/libnosys/_pthread_cleanup_push_defer.c
libgloss/libnosys/pthread_atfork.c
libgloss/libnosys/pthread_attr_destroy.c
libgloss/libnosys/pthread_attr_getaffinity_np.c
libgloss/libnosys/pthread_attr_getdetachstate.c
libgloss/libnosys/pthread_attr_getguardsize.c
libgloss/libnosys/pthread_attr_getinheritsched.c
libgloss/libnosys/pthread_attr_getschedparam.c
libgloss/libnosys/pthread_attr_getschedpolicy.c
libgloss/libnosys/pthread_attr_getscope.c
libgloss/libnosys/pthread_attr_getstack.c
libgloss/libnosys/pthread_attr_getstackaddr.c
libgloss/libnosys/pthread_attr_getstacksize.c
libgloss/libnosys/pthread_attr_init.c
libgloss/libnosys/pthread_attr_setaffinity_np.c
libgloss/libnosys/pthread_attr_setdetachstate.c
libgloss/libnosys/pthread_attr_setguardsize.c
libgloss/libnosys/pthread_attr_setinheritsched.c
libgloss/libnosys/pthread_attr_setschedparam.c
libgloss/libnosys/pthread_attr_setschedpolicy.c
libgloss/libnosys/pthread_attr_setscope.c
libgloss/libnosys/pthread_attr_setstack.c
libgloss/libnosys/pthread_attr_setstackaddr.c
libgloss/libnosys/pthread_attr_setstacksize.c
libgloss/libnosys/pthread_barrier_destroy.c
libgloss/libnosys/pthread_barrier_init.c
libgloss/libnosys/pthread_barrier_wait.c
libgloss/libnosys/pthread_barrierattr_destroy.c
libgloss/libnosys/pthread_barrierattr_getpshared.c
libgloss/libnosys/pthread_barrierattr_init.c
libgloss/libnosys/pthread_barrierattr_setpshared.c
libgloss/libnosys/pthread_cancel.c
libgloss/libnosys/pthread_cond_broadcast.c
libgloss/libnosys/pthread_cond_clockwait.c
libgloss/libnosys/pthread_cond_destroy.c
libgloss/libnosys/pthread_cond_init.c
libgloss/libnosys/pthread_cond_signal.c
libgloss/libnosys/pthread_cond_timedwait.c
libgloss/libnosys/pthread_cond_wait.c
libgloss/libnosys/pthread_condattr_destroy.c
libgloss/libnosys/pthread_condattr_getclock.c
libgloss/libnosys/pthread_condattr_getpshared.c
libgloss/libnosys/pthread_condattr_init.c
libgloss/libnosys/pthread_condattr_setclock.c
libgloss/libnosys/pthread_condattr_setpshared.c
libgloss/libnosys/pthread_create.c
libgloss/libnosys/pthread_detach.c
libgloss/libnosys/pthread_equal.c
libgloss/libnosys/pthread_exit.c
libgloss/libnosys/pthread_getaffinity_np.c
libgloss/libnosys/pthread_getattr_np.c
libgloss/libnosys/pthread_getconcurrency.c
libgloss/libnosys/pthread_getcpuclockid.c
libgloss/libnosys/pthread_getname_np.c
libgloss/libnosys/pthread_getschedparam.c
libgloss/libnosys/pthread_getspecific.c
libgloss/libnosys/pthread_join.c
libgloss/libnosys/pthread_key_create.c
libgloss/libnosys/pthread_key_delete.c
libgloss/libnosys/pthread_mutex_clocklock.c
libgloss/libnosys/pthread_mutex_destroy.c
libgloss/libnosys/pthread_mutex_getprioceiling.c
libgloss/libnosys/pthread_mutex_init.c
libgloss/libnosys/pthread_mutex_lock.c
libgloss/libnosys/pthread_mutex_setprioceiling.c
libgloss/libnosys/pthread_mutex_timedlock.c
libgloss/libnosys/pthread_mutex_trylock.c
libgloss/libnosys/pthread_mutex_unlock.c
libgloss/libnosys/pthread_mutexattr_destroy.c
libgloss/libnosys/pthread_mutexattr_getprioceiling.c
libgloss/libnosys/pthread_mutexattr_getprotocol.c
libgloss/libnosys/pthread_mutexattr_getpshared.c
libgloss/libnosys/pthread_mutexattr_gettype.c
libgloss/libnosys/pthread_mutexattr_init.c
libgloss/libnosys/pthread_mutexattr_setprioceiling.c
libgloss/libnosys/pthread_mutexattr_setprotocol.c
libgloss/libnosys/pthread_mutexattr_setpshared.c
libgloss/libnosys/pthread_mutexattr_settype.c
libgloss/libnosys/pthread_once.c
libgloss/libnosys/pthread_rwlock_clockrdlock.c
libgloss/libnosys/pthread_rwlock_clockwrlock.c
libgloss/libnosys/pthread_rwlock_destroy.c
libgloss/libnosys/pthread_rwlock_init.c
libgloss/libnosys/pthread_rwlock_rdlock.c
libgloss/libnosys/pthread_rwlock_timedrdlock.c
libgloss/libnosys/pthread_rwlock_timedwrlock.c
libgloss/libnosys/pthread_rwlock_tryrdlock.c
libgloss/libnosys/pthread_rwlock_trywrlock.c
libgloss/libnosys/pthread_rwlock_unlock.c
libgloss/libnosys/pthread_rwlock_wrlock.c
libgloss/libnosys/pthread_rwlockattr_destroy.c
libgloss/libnosys/pthread_rwlockattr_getpshared.c
libgloss/libnosys/pthread_rwlockattr_init.c
libgloss/libnosys/pthread_rwlockattr_setpshared.c
libgloss/libnosys/pthread_self.c
libgloss/libnosys/pthread_setaffinity_np.c
libgloss/libnosys/pthread_setcancelstate.c
libgloss/libnosys/pthread_setcanceltype.c
libgloss/libnosys/pthread_setconcurrency.c
libgloss/libnosys/pthread_setname_np.c
libgloss/libnosys/pthread_setschedparam.c
libgloss/libnosys/pthread_setschedprio.c
libgloss/libnosys/pthread_setspecific.c
libgloss/libnosys/pthread_spin_destroy.c
libgloss/libnosys/pthread_spin_init.c
libgloss/libnosys/pthread_spin_lock.c
libgloss/libnosys/pthread_spin_trylock.c
libgloss/libnosys/pthread_spin_unlock.c
libgloss/libnosys/pthread_testcancel.c
libgloss/libnosys/pthread_yield.c
				`),
				CFlags: []string{
					"-D__NO_SYSCALLS__",
					"-D_NO_GETUT",
					"-DHAVE_CONFIG_H",
					"-D_LIBC",
					"-D_NO_GLOB",
					"-D_NO_GETPWENT",
					"-D_NO_SIGSET",
					"-D__ESP__",
					"-D_NO_GETPASS",
					"-D_NO_POSIX_SPAWN",
					"-DHAVE_FCNTL",
					"-DHAVE_BLKSIZE",
					"-DHAVE_OPENDIR",
					"-D_GNU_SOURCE",
					"-D_LIBGLOSS",
					"-D_NO_EXECVE",
					"-D_NO_GETLOGIN",
					"-D_NO_WORDEXP",
					"-D_NO_POPEN",
					"-DHAVE_RENAME",
					"-DSIGNAL_PROVIDED",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + libcDir,
					"-I" + filepath.Join(libcDir, "xtensa"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					// TODO(MeteorsLiu): support riscv
					"-I" + filepath.Join(baseDir, "libgloss", "xtensa", "include"),
					"-I" + filepath.Join(baseDir, "libgloss", "xtensa", "boards", "esp32", "include"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: _libcCCFlags,
			},
			{
				OutputFileName: "libc-" + target + ".a",
				Files: joinFileList(libcDir, `
argz/argz_add.c
argz/argz_add_sep.c
argz/argz_append.c
argz/argz_count.c
argz/argz_create.c
argz/argz_create_sep.c
argz/argz_delete.c
argz/argz_extract.c
argz/argz_insert.c
argz/argz_next.c
argz/argz_replace.c
argz/argz_stringify.c
argz/buf_findstr.c
argz/envz_entry.c
argz/envz_get.c
argz/envz_add.c
argz/envz_remove.c
argz/envz_merge.c
argz/envz_strip.c
stdlib/__adjust.c
stdlib/__atexit.c
stdlib/__call_atexit.c
stdlib/__exp10.c
stdlib/__ten_mu.c
stdlib/_Exit.c
stdlib/abort.c
stdlib/abs.c
stdlib/aligned_alloc.c
stdlib/assert.c
stdlib/atexit.c
stdlib/atof.c
stdlib/atoff.c
stdlib/atoi.c
stdlib/atol.c
stdlib/calloc.c
stdlib/callocr.c
stdlib/cfreer.c
stdlib/div.c
stdlib/dtoa.c
stdlib/dtoastub.c
stdlib/environ.c
stdlib/envlock.c
stdlib/eprintf.c
stdlib/exit.c
stdlib/freer.c
stdlib/gdtoa-gethex.c
stdlib/gdtoa-hexnan.c
stdlib/getenv.c
stdlib/getenv_r.c
stdlib/imaxabs.c
stdlib/imaxdiv.c
stdlib/itoa.c
stdlib/labs.c
stdlib/ldiv.c
stdlib/ldtoa.c
stdlib/gdtoa-ldtoa.c
stdlib/gdtoa-gdtoa.c
stdlib/gdtoa-dmisc.c
stdlib/gdtoa-gmisc.c
stdlib/mallinfor.c
stdlib/malloc.c
stdlib/mallocr.c
stdlib/mallstatsr.c
stdlib/mblen.c
stdlib/mblen_r.c
stdlib/mbstowcs.c
stdlib/mbstowcs_r.c
stdlib/mbtowc.c
stdlib/mbtowc_r.c
stdlib/mlock.c
stdlib/mprec.c
stdlib/msizer.c
stdlib/mstats.c
stdlib/on_exit_args.c
stdlib/quick_exit.c
stdlib/rand.c
stdlib/rand_r.c
stdlib/random.c
stdlib/realloc.c
stdlib/reallocarray.c
stdlib/reallocf.c
stdlib/reallocr.c
stdlib/sb_charsets.c
stdlib/strtod.c
stdlib/strtoimax.c
stdlib/strtol.c
stdlib/strtoul.c
stdlib/strtoumax.c
stdlib/utoa.c
stdlib/wcstod.c
stdlib/wcstoimax.c
stdlib/wcstol.c
stdlib/wcstoul.c
stdlib/wcstoumax.c
stdlib/wcstombs.c
stdlib/wcstombs_r.c
stdlib/wctomb.c
stdlib/wctomb_r.c
stdlib/strtodg.c
stdlib/strtold.c
stdlib/strtorx.c
stdlib/wcstold.c
stdlib/arc4random.c
stdlib/arc4random_uniform.c
stdlib/cxa_atexit.c
stdlib/cxa_finalize.c
stdlib/drand48.c
stdlib/ecvtbuf.c
stdlib/efgcvt.c
stdlib/erand48.c
stdlib/jrand48.c
stdlib/lcong48.c
stdlib/lrand48.c
stdlib/mrand48.c
stdlib/msize.c
stdlib/mtrim.c
stdlib/nrand48.c
stdlib/rand48.c
stdlib/seed48.c
stdlib/srand48.c
stdlib/strtoll.c
stdlib/strtoll_r.c
stdlib/strtoull.c
stdlib/strtoull_r.c
stdlib/wcstoll.c
stdlib/wcstoll_r.c
stdlib/wcstoull.c
stdlib/wcstoull_r.c
stdlib/atoll.c
stdlib/llabs.c
stdlib/lldiv.c
stdlib/a64l.c
stdlib/btowc.c
stdlib/getopt.c
stdlib/getsubopt.c
stdlib/l64a.c
stdlib/malign.c
stdlib/malignr.c
stdlib/malloptr.c
stdlib/mbrlen.c
stdlib/mbrtowc.c
stdlib/mbsinit.c
stdlib/mbsnrtowcs.c
stdlib/mbsrtowcs.c
stdlib/on_exit.c
stdlib/pvallocr.c
stdlib/valloc.c
stdlib/vallocr.c
stdlib/wcrtomb.c
stdlib/wcsnrtombs.c
stdlib/wcsrtombs.c
stdlib/wctob.c
stdlib/putenv.c
stdlib/putenv_r.c
stdlib/setenv.c
stdlib/setenv_r.c
stdlib/rpmatch.c
stdlib/system.c
ctype/ctype_.c
ctype/isalnum.c
ctype/isalpha.c
ctype/iscntrl.c
ctype/isdigit.c
ctype/islower.c
ctype/isupper.c
ctype/isprint.c
ctype/ispunct.c
ctype/isspace.c
ctype/isxdigit.c
ctype/tolower.c
ctype/toupper.c
ctype/categories.c
ctype/isalnum_l.c
ctype/isalpha_l.c
ctype/isascii.c
ctype/isascii_l.c
ctype/isblank.c
ctype/isblank_l.c
ctype/iscntrl_l.c
ctype/isdigit_l.c
ctype/islower_l.c
ctype/isupper_l.c
ctype/isprint_l.c
ctype/ispunct_l.c
ctype/isspace_l.c
ctype/iswalnum.c
ctype/iswalnum_l.c
ctype/iswalpha.c
ctype/iswalpha_l.c
ctype/iswblank.c
ctype/iswblank_l.c
ctype/iswcntrl.c
ctype/iswcntrl_l.c
ctype/iswctype.c
ctype/iswctype_l.c
ctype/iswdigit.c
ctype/iswdigit_l.c
ctype/iswgraph.c
ctype/iswgraph_l.c
ctype/iswlower.c
ctype/iswlower_l.c
ctype/iswprint.c
ctype/iswprint_l.c
ctype/iswpunct.c
ctype/iswpunct_l.c
ctype/iswspace.c
ctype/iswspace_l.c
ctype/iswupper.c
ctype/iswupper_l.c
ctype/iswxdigit.c
ctype/iswxdigit_l.c
ctype/isxdigit_l.c
ctype/jp2uc.c
ctype/toascii.c
ctype/toascii_l.c
ctype/tolower_l.c
ctype/toupper_l.c
ctype/towctrans.c
ctype/towctrans_l.c
ctype/towlower.c
ctype/towlower_l.c
ctype/towupper.c
ctype/towupper_l.c
ctype/wctrans.c
ctype/wctrans_l.c
ctype/wctype.c
ctype/wctype_l.c
search/bsearch.c
search/ndbm.c
search/qsort.c
search/hash.c
search/hash_bigkey.c
search/hash_buf.c
search/hash_func.c
search/hash_log2.c
search/hash_page.c
search/hcreate.c
search/hcreate_r.c
search/tdelete.c
search/tdestroy.c
search/tfind.c
search/tsearch.c
search/twalk.c
search/bsd_qsort_r.c
search/qsort_r.c
stdio/nano-vfprintf_float.c
stdio/nano-svfprintf.c
stdio/nano-svfscanf.c
stdio/nano-vfprintf.c
stdio/nano-vfprintf_i.c
stdio/nano-vfscanf.c
stdio/nano-vfscanf_i.c
stdio/nano-vfscanf_float.c
stdio/clearerr.c
stdio/fclose.c
stdio/fdopen.c
stdio/feof.c
stdio/ferror.c
stdio/fflush.c
stdio/fgetc.c
stdio/fgetpos.c
stdio/fgets.c
stdio/fileno.c
stdio/findfp.c
stdio/flags.c
stdio/fopen.c
stdio/fprintf.c
stdio/fputc.c
stdio/fputs.c
stdio/fread.c
stdio/freopen.c
stdio/fscanf.c
stdio/fseek.c
stdio/fsetpos.c
stdio/ftell.c
stdio/fvwrite.c
stdio/fwalk.c
stdio/fwrite.c
stdio/getc.c
stdio/getchar.c
stdio/getc_u.c
stdio/getchar_u.c
stdio/getdelim.c
stdio/getline.c
stdio/gets.c
stdio/makebuf.c
stdio/perror.c
stdio/printf.c
stdio/putc.c
stdio/putchar.c
stdio/putc_u.c
stdio/putchar_u.c
stdio/puts.c
stdio/refill.c
stdio/remove.c
stdio/rename.c
stdio/rewind.c
stdio/rget.c
stdio/scanf.c
stdio/sccl.c
stdio/setbuf.c
stdio/setbuffer.c
stdio/setlinebuf.c
stdio/setvbuf.c
stdio/snprintf.c
stdio/sprintf.c
stdio/sscanf.c
stdio/stdio.c
stdio/svfiwprintf.c
stdio/svfiwscanf.c
stdio/svfwprintf.c
stdio/svfwscanf.c
stdio/tmpfile.c
stdio/tmpnam.c
stdio/ungetc.c
stdio/vdprintf.c
stdio/vfiwprintf.c
stdio/vfiwscanf.c
stdio/vfwscanf.c
stdio/vprintf.c
stdio/vscanf.c
stdio/vsnprintf.c
stdio/vsprintf.c
stdio/vsscanf.c
stdio/wbuf.c
stdio/wsetup.c
stdio/asprintf.c
stdio/fcloseall.c
stdio/fseeko.c
stdio/ftello.c
stdio/getw.c
stdio/mktemp.c
stdio/putw.c
stdio/vasprintf.c
stdio/asnprintf.c
stdio/clearerr_u.c
stdio/dprintf.c
stdio/feof_u.c
stdio/ferror_u.c
stdio/fflush_u.c
stdio/fgetc_u.c
stdio/fgets_u.c
stdio/fgetwc.c
stdio/fgetwc_u.c
stdio/fgetws.c
stdio/fgetws_u.c
stdio/fileno_u.c
stdio/fmemopen.c
stdio/fopencookie.c
stdio/fpurge.c
stdio/fputc_u.c
stdio/fputs_u.c
stdio/fputwc.c
stdio/fputwc_u.c
stdio/fputws.c
stdio/fputws_u.c
stdio/fread_u.c
stdio/fsetlocking.c
stdio/funopen.c
stdio/fwide.c
stdio/fwprintf.c
stdio/fwrite_u.c
stdio/fwscanf.c
stdio/getwc.c
stdio/getwc_u.c
stdio/getwchar.c
stdio/getwchar_u.c
stdio/open_memstream.c
stdio/putwc.c
stdio/putwc_u.c
stdio/putwchar.c
stdio/putwchar_u.c
stdio/stdio_ext.c
stdio/swprintf.c
stdio/swscanf.c
stdio/ungetwc.c
stdio/vasnprintf.c
stdio/vswprintf.c
stdio/vswscanf.c
stdio/vwprintf.c
stdio/vwscanf.c
stdio/wprintf.c
stdio/wscanf.c
string/bcopy.c
string/bzero.c
string/explicit_bzero.c
string/ffsl.c
string/ffsll.c
string/fls.c
string/flsl.c
string/flsll.c
string/index.c
string/memchr.c
string/memcmp.c
string/memmove.c
string/rindex.c
string/strcasecmp.c
string/strcat.c
string/strchr.c
string/strcoll.c
string/strcspn.c
string/strdup.c
string/strdup_r.c
string/strerror.c
string/strerror_r.c
string/strlcat.c
string/strlcpy.c
string/strlwr.c
string/strncasecmp.c
string/strncat.c
string/strncmp.c
string/strnlen.c
string/strnstr.c
string/strpbrk.c
string/strrchr.c
string/strsep.c
string/strsignal.c
string/strspn.c
string/strtok.c
string/strtok_r.c
string/strupr.c
string/strxfrm.c
string/strstr.c
string/swab.c
string/timingsafe_bcmp.c
string/timingsafe_memcmp.c
string/u_strerr.c
string/wcscat.c
string/wcschr.c
string/wcscmp.c
string/wcscoll.c
string/wcscpy.c
string/wcscspn.c
string/wcslcat.c
string/wcslcpy.c
string/wcslen.c
string/wcsncat.c
string/wcsncmp.c
string/wcsncpy.c
string/wcsnlen.c
string/wcspbrk.c
string/wcsrchr.c
string/wcsspn.c
string/wcsstr.c
string/wcstok.c
string/wcswidth.c
string/wcsxfrm.c
string/wcwidth.c
string/wmemchr.c
string/wmemcmp.c
string/wmemcpy.c
string/wmemmove.c
string/wmemset.c
string/xpg_strerror_r.c
string/bcmp.c
string/memccpy.c
string/mempcpy.c
string/stpcpy.c
string/stpncpy.c
string/strndup.c
string/strcasestr.c
string/strchrnul.c
string/strndup_r.c
string/wcpcpy.c
string/wcpncpy.c
string/wcsdup.c
string/gnu_basename.c
string/memmem.c
string/memrchr.c
string/rawmemchr.c
string/strcasecmp_l.c
string/strcoll_l.c
string/strncasecmp_l.c
string/strverscmp.c
string/strxfrm_l.c
string/wcscasecmp.c
string/wcscasecmp_l.c
string/wcscoll_l.c
string/wcsncasecmp.c
string/wcsncasecmp_l.c
string/wcsxfrm_l.c
string/wmempcpy.c
signal/psignal.c
signal/raise.c
signal/signal.c
signal/sig2str.c
time/asctime.c
time/asctime_r.c
time/clock.c
time/ctime.c
time/ctime_r.c
time/difftime.c
time/gettzinfo.c
time/gmtime.c
time/gmtime_r.c
time/lcltime.c
time/lcltime_r.c
time/mktime.c
time/month_lengths.c
time/strftime.c
time/strptime.c
time/time.c
time/tzcalc_limits.c
time/tzlock.c
time/tzset.c
time/tzset_r.c
time/tzvars.c
time/wcsftime.c
locale/locale.c
locale/localeconv.c
locale/duplocale.c
locale/freelocale.c
locale/lctype.c
locale/lmessages.c
locale/lnumeric.c
locale/lmonetary.c
locale/newlocale.c
locale/nl_langinfo.c
locale/timelocal.c
locale/uselocale.c
reent/closer.c
reent/reent.c
reent/impure.c
reent/fcntlr.c
reent/fstatr.c
reent/getentropyr.c
reent/getreent.c
reent/gettimeofdayr.c
reent/isattyr.c
reent/linkr.c
reent/lseekr.c
reent/mkdirr.c
reent/openr.c
reent/readr.c
reent/renamer.c
reent/signalr.c
reent/signgam.c
reent/sbrkr.c
reent/statr.c
reent/timesr.c
reent/unlinkr.c
reent/writer.c
reent/execr.c
errno/errno.c
misc/__dprintf.c
misc/unctrl.c
misc/ffs.c
misc/init.c
misc/fini.c
misc/lock.c
posix/closedir.c
posix/collate.c
posix/collcmp.c
posix/creat.c
posix/dirfd.c
posix/glob.c
posix/opendir.c
posix/readdir.c
posix/readdir_r.c
posix/regcomp.c
posix/regerror.c
posix/regexec.c
posix/regfree.c
posix/rewinddir.c
posix/sleep.c
posix/usleep.c
posix/telldir.c
posix/ftw.c
posix/nftw.c
posix/scandir.c
posix/seekdir.c
posix/execl.c
posix/execle.c
posix/execlp.c
posix/execv.c
posix/execve.c
posix/execvp.c
posix/wordexp.c
posix/wordfree.c
posix/popen.c
posix/posix_spawn.c
syscalls/sysclose.c
syscalls/sysfcntl.c
syscalls/sysfstat.c
syscalls/sysgetentropy.c
syscalls/sysgetpid.c
syscalls/sysgettod.c
syscalls/sysisatty.c
syscalls/syskill.c
syscalls/syslink.c
syscalls/syslseek.c
syscalls/sysopen.c
syscalls/sysread.c
syscalls/syssbrk.c
syscalls/sysstat.c
syscalls/systimes.c
syscalls/sysunlink.c
syscalls/syswrite.c
syscalls/sysexecve.c
syscalls/sysfork.c
syscalls/syswait.c
iconv/ces/utf-8.c
iconv/ces/utf-16.c
iconv/ces/ucs-2.c
iconv/ces/us-ascii.c
iconv/ces/ucs-4.c
iconv/ces/ucs-2-internal.c
iconv/ces/ucs-4-internal.c
iconv/ces/cesbi.c
iconv/ces/table.c
iconv/ces/table-pcs.c
iconv/ces/euc.c
iconv/ccs/ccsbi.c
iconv/ccs/iso_8859_10.c
iconv/ccs/iso_8859_13.c
iconv/ccs/iso_8859_14.c
iconv/ccs/iso_8859_15.c
iconv/ccs/iso_8859_1.c
iconv/ccs/iso_8859_2.c
iconv/ccs/iso_8859_3.c
iconv/ccs/iso_8859_4.c
iconv/ccs/iso_8859_5.c
iconv/ccs/iso_8859_6.c
iconv/ccs/iso_8859_7.c
iconv/ccs/iso_8859_8.c
iconv/ccs/iso_8859_9.c
iconv/ccs/iso_8859_11.c
iconv/ccs/win_1250.c
iconv/ccs/win_1252.c
iconv/ccs/win_1254.c
iconv/ccs/win_1256.c
iconv/ccs/win_1258.c
iconv/ccs/win_1251.c
iconv/ccs/win_1253.c
iconv/ccs/win_1255.c
iconv/ccs/win_1257.c
iconv/ccs/koi8_r.c
iconv/ccs/koi8_u.c
iconv/ccs/koi8_ru.c
iconv/ccs/koi8_uni.c
iconv/ccs/iso_ir_111.c
iconv/ccs/big5.c
iconv/ccs/cp775.c
iconv/ccs/cp850.c
iconv/ccs/cp852.c
iconv/ccs/cp855.c
iconv/ccs/cp866.c
iconv/ccs/jis_x0212_1990.c
iconv/ccs/jis_x0201_1976.c
iconv/ccs/jis_x0208_1990.c
iconv/ccs/ksx1001.c
iconv/ccs/cns11643_plane1.c
iconv/ccs/cns11643_plane2.c
iconv/ccs/cns11643_plane14.c
iconv/lib/aliasesi.c
iconv/lib/ucsconv.c
iconv/lib/nullconv.c
iconv/lib/iconv.c
iconv/lib/aliasesbi.c
iconv/lib/iconvnls.c
ssp/chk_fail.c
ssp/stack_protector.c
ssp/memcpy_chk.c
ssp/memmove_chk.c
ssp/mempcpy_chk.c
ssp/memset_chk.c
ssp/stpcpy_chk.c
ssp/stpncpy_chk.c
ssp/strcat_chk.c
ssp/strcpy_chk.c
ssp/strncat_chk.c
ssp/strncpy_chk.c
ssp/gets_chk.c
ssp/snprintf_chk.c
ssp/sprintf_chk.c
ssp/vsnprintf_chk.c
ssp/vsprintf_chk.c
machine/xtensa/memcpy.S
machine/xtensa/memset.S
machine/xtensa/setjmp.S
machine/xtensa/strcmp.S
machine/xtensa/strcpy.S
machine/xtensa/strlen.S
machine/xtensa/strncpy.S
				`),
				CFlags: []string{
					"-DHAVE_CONFIG_H",
					"-D_LIBC",
					"-D__NO_SYSCALLS__",
					"-D_NO_GLOB",
					"-D_NO_EXECVE",
					"-D_NO_GETLOGIN",
					"-D_NO_GETPWENT",
					"-D_NO_GETUT",
					"-D_NO_GETPASS",
					"-D_NO_SIGSET",
					"-D_NO_WORDEXP",
					"-D_NO_POPEN",
					"-D_NO_POSIX_SPAWN",
					"-DHAVE_FCNTL",
					"-DHAVE_BLKSIZE",
					"-DHAVE_OPENDIR",
					"-DHAVE_RENAME",
					"-DSIGNAL_PROVIDED",
					"-D__ESP__",
					"-isystem" + filepath.Join(libcDir, "include"),
					"-I" + filepath.Join(baseDir, "newlib"),
					"-I" + libcDir,
					"-I" + filepath.Join(libcDir, "xtensa"),
					"-I" + filepath.Join(baseDir, "libgloss"),
					// TODO(MeteorsLiu): support riscv
					"-idirafter" + filepath.Join(baseDir, "include"),
					"-I" + filepath.Join(libcDir, "ssp"),
					"-I" + filepath.Join(libcDir, "locale"),
					"-I" + filepath.Join(libcDir, "errno"),
					"-I" + filepath.Join(libcDir, "syscalls"),
					"-I" + filepath.Join(libcDir, "iconv", "lib"),
					"-I" + filepath.Join(libcDir, "argz"),
					"-I" + filepath.Join(libcDir, "stdio"),
					"-I" + filepath.Join(libcDir, "iconv", "ccs"),
					"-I" + filepath.Join(libcDir, "ctype"),
					"-I" + filepath.Join(libcDir, "signal"),
					"-I" + filepath.Join(libcDir, "time"),
					"-I" + filepath.Join(libcDir, "reent"),
					"-I" + filepath.Join(libcDir, "machine", "xtensa", "include"),
					"-I" + filepath.Join(libcDir, "string"),
					"-I" + filepath.Join(libcDir, "iconv", "ces"),
					"-I" + filepath.Join(libcDir, "search"),
					"-I" + filepath.Join(libcDir, "misc"),
					"-I" + filepath.Join(libcDir, "posix"),
					"-I" + filepath.Join(libcDir, "stdlib"),
				},
				LDFlags: _libcLDFlags,
				CCFlags: withDefaultCCFlags([]string{
					"-fno-builtin",
					"-Wno-implicit-function-declaration",
					"-Wno-int-conversion",
					"-Wno-unused-command-line-argument",
				}),
			},
		},
	}
}

// getNewlibESP32Config returns configuration for newlib esp32
func GetNewlibESP32CompileConfig(baseDir, target, mcpu string) compile.CompileConfig {
	if strings.Contains(target, "riscv32") {
		return getNewlibESP32ConfigRISCV(baseDir, target)
	}
	return getNewlibESP32ConfigXtensa(baseDir, target)
}
