// Code generated by /tmp/gen_syscall_symbols_from_types.go; DO NOT EDIT.
//go:build linux && amd64

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_linuxamd64_Part01(t *testing.T) {
	_ = t
	_ = syscall.ARPHRD_IEEE802154_PHY
	_ = syscall.Dup2
	_ = syscall.EPOLL_NONBLOCK
	_ = syscall.Ioperm
	_ = syscall.Iopl
	_ = syscall.MAP_32BIT
	_ = syscall.PTRACE_ARCH_PRCTL
	_ = syscall.PTRACE_GETFPREGS
	_ = syscall.PTRACE_GETFPXREGS
	_ = syscall.PTRACE_GET_THREAD_AREA
	_ = syscall.PTRACE_OLDSETOPTIONS
	_ = syscall.PTRACE_SETFPREGS
	_ = syscall.PTRACE_SETFPXREGS
	_ = syscall.PTRACE_SET_THREAD_AREA
	_ = syscall.PTRACE_SINGLEBLOCK
	_ = syscall.PTRACE_SYSEMU
	_ = syscall.PTRACE_SYSEMU_SINGLESTEP
	_ = syscall.SYS_ACCESS
	_ = syscall.SYS_AFS_SYSCALL
	_ = syscall.SYS_ALARM
	_ = syscall.SYS_ARCH_PRCTL
	_ = syscall.SYS_CHMOD
	_ = syscall.SYS_CHOWN
	_ = syscall.SYS_CREAT
	_ = syscall.SYS_CREATE_MODULE
	_ = syscall.SYS_DUP2
	_ = syscall.SYS_EPOLL_CREATE
	_ = syscall.SYS_EPOLL_CTL_OLD
	_ = syscall.SYS_EPOLL_WAIT
	_ = syscall.SYS_EPOLL_WAIT_OLD
	_ = syscall.SYS_EVENTFD
	_ = syscall.SYS_FORK
	_ = syscall.SYS_FUTIMESAT
	_ = syscall.SYS_GETDENTS
	_ = syscall.SYS_GETPGRP
	_ = syscall.SYS_GETPMSG
	_ = syscall.SYS_GET_KERNEL_SYMS
	_ = syscall.SYS_GET_THREAD_AREA
	_ = syscall.SYS_INOTIFY_INIT
	_ = syscall.SYS_IOPERM
	_ = syscall.SYS_IOPL
	_ = syscall.SYS_LCHOWN
	_ = syscall.SYS_LINK
	_ = syscall.SYS_LSTAT
	_ = syscall.SYS_MKDIR
	_ = syscall.SYS_MKNOD
	_ = syscall.SYS_MODIFY_LDT
	_ = syscall.SYS_NEWFSTATAT
	_ = syscall.SYS_OPEN
	_ = syscall.SYS_PAUSE
	_ = syscall.SYS_PIPE
	_ = syscall.SYS_POLL
	_ = syscall.SYS_PUTPMSG
	_ = syscall.SYS_QUERY_MODULE
	_ = syscall.SYS_READLINK
	_ = syscall.SYS_RENAME
	_ = syscall.SYS_RMDIR
	_ = syscall.SYS_SECURITY
	_ = syscall.SYS_SELECT
	_ = syscall.SYS_SET_THREAD_AREA
	_ = syscall.SYS_SIGNALFD
	_ = syscall.SYS_STAT
	_ = syscall.SYS_SYMLINK
	_ = syscall.SYS_SYSFS
	_ = syscall.SYS_TIME
	_ = syscall.SYS_TUXCALL
	_ = syscall.SYS_UNLINK
	_ = syscall.SYS_USELIB
	_ = syscall.SYS_USTAT
	_ = syscall.SYS_UTIME
	_ = syscall.SYS_UTIMES
	_ = syscall.SYS_VFORK
	_ = syscall.SYS_VSERVER
	_ = syscall.SYS__SYSCTL
	_ = syscall.Ustat
}
