// Code generated by /tmp/gen_syscall_symbols_from_types.go; DO NOT EDIT.
//go:build darwin && arm64

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_darwinarm64_Part01(t *testing.T) {
	_ = t
	_ = syscall.AF_UTUN
	_ = syscall.EQFULL
	_ = syscall.F_FINDSIGS
	_ = syscall.F_GETCODEDIR
	_ = syscall.F_GETPROTECTIONLEVEL
	_ = syscall.F_SETLKWTIMEOUT
	_ = syscall.F_SINGLE_WRITER
	_ = syscall.F_TRANSCODEKEY
	_ = syscall.NOTE_BACKGROUND
	_ = syscall.NOTE_CRITICAL
	_ = syscall.NOTE_EXIT_CSERROR
	_ = syscall.NOTE_EXIT_DECRYPTFAIL
	_ = syscall.NOTE_EXIT_DETAIL
	_ = syscall.NOTE_EXIT_DETAIL_MASK
	_ = syscall.NOTE_EXIT_MEMORY
	_ = syscall.NOTE_EXIT_REPARENTED
	_ = syscall.NOTE_LEEWAY
	_ = syscall.O_DP_GETRAWENCRYPTED
	_ = syscall.RLIMIT_CPU_USAGE_MONITOR
	_ = syscall.RTF_PROXY
	_ = syscall.RTF_ROUTER
	_ = syscall.SIOCIFGCLONERS
	_ = syscall.SO_NUMRCVPKT
	_ = syscall.SYS_CSOPS_AUDITTOKEN
	_ = syscall.SYS_KAS_INFO
	_ = syscall.SYS_LEDGER
	_ = syscall.SYS_OPEN_DPROTECTED_NP
	_ = syscall.TCP_ENABLE_ECN
	_ = syscall.TCP_KEEPCNT
	_ = syscall.TCP_KEEPINTVL
	_ = syscall.TCP_NOTSENT_LOWAT
	_ = syscall.TCP_SENDMOREACKS
}
