// Code generated by /tmp/gen_syscall_symbols_from_types.go; DO NOT EDIT.
//go:build darwin && amd64

package syscall_test

import (
	"syscall"
	"testing"
)

func TestPublicAPISymbols_darwinamd64_Part01(t *testing.T) {
	_ = t
	_ = syscall.F_MARKDEPENDENCY
	_ = syscall.F_READBOOTSTRAP
	_ = syscall.F_WRITEBOOTSTRAP
	_ = syscall.NOTE_RESOURCEEND
	_ = syscall.SIOCALIFADDR
	_ = syscall.SIOCDLIFADDR
	_ = syscall.SIOCGETSGCNT
	_ = syscall.SIOCGETVIFCNT
	_ = syscall.SIOCGLIFADDR
	_ = syscall.SIOCGLIFPHYADDR
	_ = syscall.SIOCSLIFPHYADDR
	_ = syscall.SO_RESTRICTIONS
	_ = syscall.SO_RESTRICT_DENYIN
	_ = syscall.SO_RESTRICT_DENYOUT
	_ = syscall.SO_RESTRICT_DENYSET
	_ = syscall.SYS_ADD_PROFIL
	_ = syscall.SYS_FSTATV
	_ = syscall.SYS_GETAUDIT
	_ = syscall.SYS_LSTATV
	_ = syscall.SYS_MKCOMPLEX
	_ = syscall.SYS_PROFIL
	_ = syscall.SYS_SETAUDIT
	_ = syscall.SYS_STATV
	_ = syscall.TCP_MINMSSOVERLOAD
}
