// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.go from LPC15xx_v0.7.svd, see https://github.com/posborne/cmsis-svd/tree/master/data/NXP

/*
// LPC15xx Cortex-M3 MCU; up to 64 kB flash; up to 12 kB SRAM; USB device; USART; EEPROM
*/



.syntax unified

// This is the default handler for interrupts, if triggered but not defined.
.section .text.Default_Handler
.global  Default_Handler
.type    Default_Handler, %function
Default_Handler:
    wfe
    b    Default_Handler
.size Default_Handler, .-Default_Handler

// Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, Default_Handler
.endm

// Must set the "a" flag on the section:
// https://svnweb.freebsd.org/base/stable/11/sys/arm/arm/locore-v4.S?r1=321049&r2=321048&pathrev=321049
// https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
.section .isr_vector, "a", %progbits
.global  __isr_vector
__isr_vector:
    // Interrupt vector as defined by Cortex-M, starting with the stack top.
    // On reset, SP is initialized with *0x0 and PC is loaded with *0x4, loading
    // _stack_top and Reset_Handler.
    .long _stack_top
    .long Reset_Handler
    .long NMI_Handler
    .long HardFault_Handler
    .long MemoryManagement_Handler
    .long BusFault_Handler
    .long UsageFault_Handler
    .long 0
    .long 0
    .long 0
    .long 0
    .long SVC_Handler
    .long DebugMon_Handler
    .long 0
    .long PendSV_Handler
    .long SysTick_Handler

    // Extra interrupts for peripherals defined by the hardware vendor.
    .long WDT_IRQHandler
    .long BOD_IRQ_IRQHandler
    .long FLASH_IRQHandler
    .long EE_IRQHandler
    .long DMA_IRQHandler
    .long GINT0_IRQHandler
    .long GINT1_IRQHandler
    .long PIN_INT0_IRQHandler
    .long PIN_INT1_IRQHandler
    .long PIN_INT2_IRQHandler
    .long PIN_INT3_IRQHandler
    .long PIN_INT4_IRQHandler
    .long PIN_INT5_IRQHandler
    .long PIN_INT6_IRQHandler
    .long PIN_INT7_IRQHandler
    .long RIT_IRQHandler
    .long SCT0_IRQHandler
    .long SCT1_IRQHandler
    .long SCT2_IRQHandler
    .long SCT3_IRQHandler
    .long MRT_IRQHandler
    .long UART0_IRQHandler
    .long UART1_IRQHandler
    .long UART2_IRQHandler
    .long I2C0_IRQHandler
    .long SPI0_IRQHandler
    .long SPI1_IRQHandler
    .long C_CAN0_IRQHandler
    .long USB_IRQ_IRQHandler
    .long USB_FIQ_IRQHandler
    .long USBWAKEUP_IRQHandler
    .long ADC0_SEQA_IRQHandler
    .long ADC0_SEQB_IRQHandler
    .long ADC0_THCMP_IRQHandler
    .long ADC0_OVR_IRQHandler
    .long ADC1_SEQA_IRQHandler
    .long ADC1_SEQB_IRQHandler
    .long ADC1_THCMP_IRQHandler
    .long ADC1_OVR_IRQHandler
    .long DAC_IRQHandler
    .long CMP0_IRQHandler
    .long CMP1_IRQHandler
    .long CMP2_IRQHandler
    .long CMP3_IRQHandler
    .long QEI_IRQHandler
    .long RTC_ALARM_IRQHandler
    .long RTC_WAKE_IRQHandler

    // Define default implementations for interrupts, redirecting to
    // Default_Handler when not implemented.
    IRQ NMI_Handler
    IRQ HardFault_Handler
    IRQ MemoryManagement_Handler
    IRQ BusFault_Handler
    IRQ UsageFault_Handler
    IRQ SVC_Handler
    IRQ DebugMon_Handler
    IRQ PendSV_Handler
    IRQ SysTick_Handler
    IRQ WDT_IRQHandler
    IRQ BOD_IRQ_IRQHandler
    IRQ FLASH_IRQHandler
    IRQ EE_IRQHandler
    IRQ DMA_IRQHandler
    IRQ GINT0_IRQHandler
    IRQ GINT1_IRQHandler
    IRQ PIN_INT0_IRQHandler
    IRQ PIN_INT1_IRQHandler
    IRQ PIN_INT2_IRQHandler
    IRQ PIN_INT3_IRQHandler
    IRQ PIN_INT4_IRQHandler
    IRQ PIN_INT5_IRQHandler
    IRQ PIN_INT6_IRQHandler
    IRQ PIN_INT7_IRQHandler
    IRQ RIT_IRQHandler
    IRQ SCT0_IRQHandler
    IRQ SCT1_IRQHandler
    IRQ SCT2_IRQHandler
    IRQ SCT3_IRQHandler
    IRQ MRT_IRQHandler
    IRQ UART0_IRQHandler
    IRQ UART1_IRQHandler
    IRQ UART2_IRQHandler
    IRQ I2C0_IRQHandler
    IRQ SPI0_IRQHandler
    IRQ SPI1_IRQHandler
    IRQ C_CAN0_IRQHandler
    IRQ USB_IRQ_IRQHandler
    IRQ USB_FIQ_IRQHandler
    IRQ USBWAKEUP_IRQHandler
    IRQ ADC0_SEQA_IRQHandler
    IRQ ADC0_SEQB_IRQHandler
    IRQ ADC0_THCMP_IRQHandler
    IRQ ADC0_OVR_IRQHandler
    IRQ ADC1_SEQA_IRQHandler
    IRQ ADC1_SEQB_IRQHandler
    IRQ ADC1_THCMP_IRQHandler
    IRQ ADC1_OVR_IRQHandler
    IRQ DAC_IRQHandler
    IRQ CMP0_IRQHandler
    IRQ CMP1_IRQHandler
    IRQ CMP2_IRQHandler
    IRQ CMP3_IRQHandler
    IRQ QEI_IRQHandler
    IRQ RTC_ALARM_IRQHandler
    IRQ RTC_WAKE_IRQHandler

.size __isr_vector, .-__isr_vector
