// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.go from LPC176x5x_v0.2.svd, see https://github.com/posborne/cmsis-svd/tree/master/data/NXP

/*
// LPC176x/LPC175x M3
*/



.syntax unified

// This is the default handler for interrupts, if triggered but not defined.
.section .text.Default_Handler
.global  Default_Handler
.type    Default_Handler, %function
Default_Handler:
    wfe
    b    Default_Handler
.size Default_Handler, .-Default_Handler

// Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, Default_Handler
.endm

// Must set the "a" flag on the section:
// https://svnweb.freebsd.org/base/stable/11/sys/arm/arm/locore-v4.S?r1=321049&r2=321048&pathrev=321049
// https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
.section .isr_vector, "a", %progbits
.global  __isr_vector
__isr_vector:
    // Interrupt vector as defined by Cortex-M, starting with the stack top.
    // On reset, SP is initialized with *0x0 and PC is loaded with *0x4, loading
    // _stack_top and Reset_Handler.
    .long _stack_top
    .long Reset_Handler
    .long NMI_Handler
    .long HardFault_Handler
    .long MemoryManagement_Handler
    .long BusFault_Handler
    .long UsageFault_Handler
    .long 0
    .long 0
    .long 0
    .long 0
    .long SVC_Handler
    .long DebugMon_Handler
    .long 0
    .long PendSV_Handler
    .long SysTick_Handler

    // Extra interrupts for peripherals defined by the hardware vendor.
    .long WDT_IRQHandler
    .long TIMER0_IRQHandler
    .long TIMER1_IRQHandler
    .long TIMER2_IRQHandler
    .long TIMER3_IRQHandler
    .long UART0_IRQHandler
    .long UART1_IRQHandler
    .long UART2_IRQHandler
    .long UART3_IRQHandler
    .long PWM1_IRQHandler
    .long I2C0_IRQHandler
    .long I2C1_IRQHandler
    .long I2C2_IRQHandler
    .long SPI_IRQHandler
    .long SSP0_IRQHandler
    .long SSP1_IRQHandler
    .long PLL0_IRQHandler
    .long RTC_IRQHandler
    .long EINT0_IRQHandler
    .long EINT1_IRQHandler
    .long EINT2_IRQHandler
    .long EINT3_IRQHandler
    .long ADC_IRQHandler
    .long BOD_IRQHandler
    .long USB_IRQHandler
    .long CAN_IRQHandler
    .long DMA_IRQHandler
    .long I2S_IRQHandler
    .long ENET_IRQHandler
    .long RIT_IRQHandler
    .long MCPWM_IRQHandler
    .long QEI_IRQHandler
    .long PLL1_IRQHandler
    .long USBActivity_IRQHandler
    .long CANActivity_IRQHandler

    // Define default implementations for interrupts, redirecting to
    // Default_Handler when not implemented.
    IRQ NMI_Handler
    IRQ HardFault_Handler
    IRQ MemoryManagement_Handler
    IRQ BusFault_Handler
    IRQ UsageFault_Handler
    IRQ SVC_Handler
    IRQ DebugMon_Handler
    IRQ PendSV_Handler
    IRQ SysTick_Handler
    IRQ WDT_IRQHandler
    IRQ TIMER0_IRQHandler
    IRQ TIMER1_IRQHandler
    IRQ TIMER2_IRQHandler
    IRQ TIMER3_IRQHandler
    IRQ UART0_IRQHandler
    IRQ UART1_IRQHandler
    IRQ UART2_IRQHandler
    IRQ UART3_IRQHandler
    IRQ PWM1_IRQHandler
    IRQ I2C0_IRQHandler
    IRQ I2C1_IRQHandler
    IRQ I2C2_IRQHandler
    IRQ SPI_IRQHandler
    IRQ SSP0_IRQHandler
    IRQ SSP1_IRQHandler
    IRQ PLL0_IRQHandler
    IRQ RTC_IRQHandler
    IRQ EINT0_IRQHandler
    IRQ EINT1_IRQHandler
    IRQ EINT2_IRQHandler
    IRQ EINT3_IRQHandler
    IRQ ADC_IRQHandler
    IRQ BOD_IRQHandler
    IRQ USB_IRQHandler
    IRQ CAN_IRQHandler
    IRQ DMA_IRQHandler
    IRQ I2S_IRQHandler
    IRQ ENET_IRQHandler
    IRQ RIT_IRQHandler
    IRQ MCPWM_IRQHandler
    IRQ QEI_IRQHandler
    IRQ PLL1_IRQHandler
    IRQ USBActivity_IRQHandler
    IRQ CANActivity_IRQHandler

.size __isr_vector, .-__isr_vector
