// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.go from LPC800_v0.3.svd, see https://github.com/posborne/cmsis-svd/tree/master/data/NXP

/*
// LPC800
*/



.syntax unified

// This is the default handler for interrupts, if triggered but not defined.
.section .text.Default_Handler
.global  Default_Handler
.type    Default_Handler, %function
Default_Handler:
    wfe
    b    Default_Handler
.size Default_Handler, .-Default_Handler

// Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, Default_Handler
.endm

// Must set the "a" flag on the section:
// https://svnweb.freebsd.org/base/stable/11/sys/arm/arm/locore-v4.S?r1=321049&r2=321048&pathrev=321049
// https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
.section .isr_vector, "a", %progbits
.global  __isr_vector
__isr_vector:
    // Interrupt vector as defined by Cortex-M, starting with the stack top.
    // On reset, SP is initialized with *0x0 and PC is loaded with *0x4, loading
    // _stack_top and Reset_Handler.
    .long _stack_top
    .long Reset_Handler
    .long NMI_Handler
    .long HardFault_Handler
    .long MemoryManagement_Handler
    .long BusFault_Handler
    .long UsageFault_Handler
    .long 0
    .long 0
    .long 0
    .long 0
    .long SVC_Handler
    .long DebugMon_Handler
    .long 0
    .long PendSV_Handler
    .long SysTick_Handler

    // Extra interrupts for peripherals defined by the hardware vendor.
    .long SPI0_IRQHandler
    .long SPI1_IRQHandler
    .long 0
    .long UART0_IRQHandler
    .long UART1_IRQHandler
    .long UART2_IRQHandler
    .long 0
    .long 0
    .long I2C_IRQHandler
    .long SCT_IRQHandler
    .long MRT_IRQHandler
    .long CMP_IRQHandler
    .long WDT_IRQHandler
    .long BOD_IRQHandler
    .long FLASH_IRQ_IRQHandler
    .long WKT_IRQHandler
    .long 0
    .long 0
    .long 0
    .long 0
    .long 0
    .long 0
    .long 0
    .long 0
    .long PININT0_IRQHandler
    .long PININT1_IRQHandler
    .long PININT2_IRQHandler
    .long PININT3_IRQHandler
    .long PININT4_IRQHandler
    .long PININT5_IRQHandler
    .long PININT6_IRQHandler
    .long PININT7_IRQHandler

    // Define default implementations for interrupts, redirecting to
    // Default_Handler when not implemented.
    IRQ NMI_Handler
    IRQ HardFault_Handler
    IRQ MemoryManagement_Handler
    IRQ BusFault_Handler
    IRQ UsageFault_Handler
    IRQ SVC_Handler
    IRQ DebugMon_Handler
    IRQ PendSV_Handler
    IRQ SysTick_Handler
    IRQ SPI0_IRQHandler
    IRQ SPI1_IRQHandler
    IRQ UART0_IRQHandler
    IRQ UART1_IRQHandler
    IRQ UART2_IRQHandler
    IRQ I2C_IRQHandler
    IRQ SCT_IRQHandler
    IRQ MRT_IRQHandler
    IRQ CMP_IRQHandler
    IRQ WDT_IRQHandler
    IRQ BOD_IRQHandler
    IRQ FLASH_IRQ_IRQHandler
    IRQ WKT_IRQHandler
    IRQ PININT0_IRQHandler
    IRQ PININT1_IRQHandler
    IRQ PININT2_IRQHandler
    IRQ PININT3_IRQHandler
    IRQ PININT4_IRQHandler
    IRQ PININT5_IRQHandler
    IRQ PININT6_IRQHandler
    IRQ PININT7_IRQHandler

.size __isr_vector, .-__isr_vector
