coverage:
  ignore:
    - "chore"
    - "cmd"
    - "cl/cltest"
    - "internal/build"
    - "internal/llgen"
    - "internal/mockable"
    - "internal/packages"
    - "internal/typepatch"
    - "internal/github"
    - "xtool"
