; Automatically generated file. DO NOT EDIT.
; Generated by gen-device-avr.go from ATmega8HVA.atdf, see http://packs.download.atmel.com/

; This is the default handler for interrupts, if triggered but not defined.
; Sleep inside so that an accidentally triggered interrupt won't drain the
; battery of a battery-powered device.
.section .text.__vector_default
.global  __vector_default
__vector_default:
    sleep
    rjmp __vector_default

; Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, __vector_default
.endm

; The interrupt vector of this device. Must be placed at address 0 by the linker.
.section .vectors, "a", %progbits
.global  __vectors
    rjmp __vector_RESET
    rjmp __vector_BPINT
    rjmp __vector_VREGMON
    rjmp __vector_INT0
    rjmp __vector_INT1
    rjmp __vector_INT2
    rjmp __vector_WDT
    rjmp __vector_TIMER1_IC
    rjmp __vector_TIMER1_COMPA
    rjmp __vector_TIMER1_COMPB
    rjmp __vector_TIMER1_OVF
    rjmp __vector_TIMER0_IC
    rjmp __vector_TIMER0_COMPA
    rjmp __vector_TIMER0_COMPB
    rjmp __vector_TIMER0_OVF
    rjmp __vector_SPI_STC
    rjmp __vector_VADC
    rjmp __vector_CCADC_CONV
    rjmp __vector_CCADC_REG_CUR
    rjmp __vector_CCADC_ACC
    rjmp __vector_EE_READY

    ; Define default implementations for interrupts, redirecting to
    ; __vector_default when not implemented.
    IRQ __vector_RESET
    IRQ __vector_BPINT
    IRQ __vector_VREGMON
    IRQ __vector_INT0
    IRQ __vector_INT1
    IRQ __vector_INT2
    IRQ __vector_WDT
    IRQ __vector_TIMER1_IC
    IRQ __vector_TIMER1_COMPA
    IRQ __vector_TIMER1_COMPB
    IRQ __vector_TIMER1_OVF
    IRQ __vector_TIMER0_IC
    IRQ __vector_TIMER0_COMPA
    IRQ __vector_TIMER0_COMPB
    IRQ __vector_TIMER0_OVF
    IRQ __vector_SPI_STC
    IRQ __vector_VADC
    IRQ __vector_CCADC_CONV
    IRQ __vector_CCADC_REG_CUR
    IRQ __vector_CCADC_ACC
    IRQ __vector_EE_READY
