; Automatically generated file. DO NOT EDIT.
; Generated by gen-device-avr.go from ATtiny841.atdf, see http://packs.download.atmel.com/

; This is the default handler for interrupts, if triggered but not defined.
; Sleep inside so that an accidentally triggered interrupt won't drain the
; battery of a battery-powered device.
.section .text.__vector_default
.global  __vector_default
__vector_default:
    sleep
    rjmp __vector_default

; Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, __vector_default
.endm

; The interrupt vector of this device. Must be placed at address 0 by the linker.
.section .vectors, "a", %progbits
.global  __vectors
    rjmp __vector_RESET
    rjmp __vector_INT0
    rjmp __vector_PCINT0
    rjmp __vector_PCINT1
    rjmp __vector_WDT
    rjmp __vector_TIMER1_CAPT
    rjmp __vector_TIMER1_COMPA
    rjmp __vector_TIMER1_COMPB
    rjmp __vector_TIMER1_OVF
    rjmp __vector_TIMER0_COMPA
    rjmp __vector_TIMER0_COMPB
    rjmp __vector_TIMER0_OVF
    rjmp __vector_ANA_COMP0
    rjmp __vector_ADC
    rjmp __vector_EE_RDY
    rjmp __vector_ANA_COMP1
    rjmp __vector_TIMER2_CAPT
    rjmp __vector_TIMER2_COMPA
    rjmp __vector_TIMER2_COMPB
    rjmp __vector_TIMER2_OVF
    rjmp __vector_SPI
    rjmp __vector_USART0_START
    rjmp __vector_USART0_RX
    rjmp __vector_USART0_UDRE
    rjmp __vector_USART0_TX
    rjmp __vector_USART1_START
    rjmp __vector_USART1_RX
    rjmp __vector_USART1_UDRE
    rjmp __vector_USART1_TX
    rjmp __vector_TWI_SLAVE

    ; Define default implementations for interrupts, redirecting to
    ; __vector_default when not implemented.
    IRQ __vector_RESET
    IRQ __vector_INT0
    IRQ __vector_PCINT0
    IRQ __vector_PCINT1
    IRQ __vector_WDT
    IRQ __vector_TIMER1_CAPT
    IRQ __vector_TIMER1_COMPA
    IRQ __vector_TIMER1_COMPB
    IRQ __vector_TIMER1_OVF
    IRQ __vector_TIMER0_COMPA
    IRQ __vector_TIMER0_COMPB
    IRQ __vector_TIMER0_OVF
    IRQ __vector_ANA_COMP0
    IRQ __vector_ADC
    IRQ __vector_EE_RDY
    IRQ __vector_ANA_COMP1
    IRQ __vector_TIMER2_CAPT
    IRQ __vector_TIMER2_COMPA
    IRQ __vector_TIMER2_COMPB
    IRQ __vector_TIMER2_OVF
    IRQ __vector_SPI
    IRQ __vector_USART0_START
    IRQ __vector_USART0_RX
    IRQ __vector_USART0_UDRE
    IRQ __vector_USART0_TX
    IRQ __vector_USART1_START
    IRQ __vector_USART1_RX
    IRQ __vector_USART1_UDRE
    IRQ __vector_USART1_TX
    IRQ __vector_TWI_SLAVE
