; Automatically generated file. DO NOT EDIT.
; Generated by gen-device-avr.go from ATtiny1616.atdf, see http://packs.download.atmel.com/

; This is the default handler for interrupts, if triggered but not defined.
; Sleep inside so that an accidentally triggered interrupt won't drain the
; battery of a battery-powered device.
.section .text.__vector_default
.global  __vector_default
__vector_default:
    sleep
    rjmp __vector_default

; Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, __vector_default
.endm

; The interrupt vector of this device. Must be placed at address 0 by the linker.
.section .vectors, "a", %progbits
.global  __vectors
    jmp __vector_RESET
    jmp __vector_CRCSCAN_NMI
    jmp __vector_BOD_VLM
    jmp __vector_PORTA_PORT
    jmp __vector_PORTB_PORT
    jmp __vector_PORTC_PORT
    jmp __vector_RTC_CNT
    jmp __vector_RTC_PIT
    jmp __vector_TCA0_LUNF
    jmp __vector_TCA0_HUNF
    jmp __vector_TCA0_LCMP0
    jmp __vector_TCA0_CMP1
    jmp __vector_TCA0_CMP2
    jmp __vector_TCB0_INT
    jmp __vector_TCB1_INT
    jmp __vector_TCD0_OVF
    jmp __vector_TCD0_TRIG
    jmp __vector_AC0_AC
    jmp __vector_AC1_AC
    jmp __vector_AC2_AC
    jmp __vector_ADC0_RESRDY
    jmp __vector_ADC0_WCOMP
    jmp __vector_ADC1_RESRDY
    jmp __vector_ADC1_WCOMP
    jmp __vector_TWI0_TWIS
    jmp __vector_TWI0_TWIM
    jmp __vector_SPI0_INT
    jmp __vector_USART0_RXC
    jmp __vector_USART0_DRE
    jmp __vector_USART0_TXC
    jmp __vector_NVMCTRL_EE

    ; Define default implementations for interrupts, redirecting to
    ; __vector_default when not implemented.
    IRQ __vector_RESET
    IRQ __vector_CRCSCAN_NMI
    IRQ __vector_BOD_VLM
    IRQ __vector_PORTA_PORT
    IRQ __vector_PORTB_PORT
    IRQ __vector_PORTC_PORT
    IRQ __vector_RTC_CNT
    IRQ __vector_RTC_PIT
    IRQ __vector_TCA0_LUNF
    IRQ __vector_TCA0_OVF
    IRQ __vector_TCA0_HUNF
    IRQ __vector_TCA0_LCMP0
    IRQ __vector_TCA0_CMP0
    IRQ __vector_TCA0_CMP1
    IRQ __vector_TCA0_LCMP1
    IRQ __vector_TCA0_CMP2
    IRQ __vector_TCA0_LCMP2
    IRQ __vector_TCB0_INT
    IRQ __vector_TCB1_INT
    IRQ __vector_TCD0_OVF
    IRQ __vector_TCD0_TRIG
    IRQ __vector_AC0_AC
    IRQ __vector_AC1_AC
    IRQ __vector_AC2_AC
    IRQ __vector_ADC0_RESRDY
    IRQ __vector_ADC0_WCOMP
    IRQ __vector_ADC1_RESRDY
    IRQ __vector_ADC1_WCOMP
    IRQ __vector_TWI0_TWIS
    IRQ __vector_TWI0_TWIM
    IRQ __vector_SPI0_INT
    IRQ __vector_USART0_RXC
    IRQ __vector_USART0_DRE
    IRQ __vector_USART0_TXC
    IRQ __vector_NVMCTRL_EE
