name: "Setup Embedded Dependencies"
description: "Install dependencies required for embedded QEMU tests"

runs:
  using: "composite"
  steps:
    - name: Install macOS embedded dependencies
      if: runner.os == 'macOS'
      shell: bash
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        brew update
        brew install sdl2

    - name: Install Ubuntu embedded dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-2.0-0

    - name: Install ESP QEMU toolchains
      shell: bash
      run: |
        chmod +x .github/workflows/install-esp-qemu.sh
        QEMU_DIR=".cache/qemu"
        .github/workflows/install-esp-qemu.sh "$QEMU_DIR"
        echo "${PWD}/${QEMU_DIR}/bin" >> $GITHUB_PATH

    - name: Verify ESP QEMU installation
      shell: bash
      run: |
        which qemu-system-riscv32
        which qemu-system-xtensa
        qemu-system-riscv32 --version
        qemu-system-xtensa --version
