// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.go from R7FA4W1AD.svd, see https://github.com/cmsis-svd/cmsis-svd-data/tree/master/data/Renesas

/*
// ARM 32-bit Cortex-M4F Microcontroller based device, CPU clock up to 48MHz, etc. 
*/



.syntax unified

// This is the default handler for interrupts, if triggered but not defined.
.section .text.Default_Handler
.global  Default_Handler
.type    Default_Handler, %function
Default_Handler:
    wfe
    b    Default_Handler
.size Default_Handler, .-Default_Handler

// Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, Default_Handler
.endm

// Must set the "a" flag on the section:
// https://svnweb.freebsd.org/base/stable/11/sys/arm/arm/locore-v4.S?r1=321049&r2=321048&pathrev=321049
// https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
.section .isr_vector, "a", %progbits
.global  __isr_vector
__isr_vector:
    // Interrupt vector as defined by Cortex-M, starting with the stack top.
    // On reset, SP is initialized with *0x0 and PC is loaded with *0x4, loading
    // _stack_top and Reset_Handler.
    .long _stack_top
    .long Reset_Handler
    .long NMI_Handler
    .long HardFault_Handler
    .long MemoryManagement_Handler
    .long BusFault_Handler
    .long UsageFault_Handler
    .long 0
    .long 0
    .long 0
    .long 0
    .long SVC_Handler
    .long DebugMon_Handler
    .long 0
    .long PendSV_Handler
    .long SysTick_Handler

    // Extra interrupts for peripherals defined by the hardware vendor.
    .long IEL0_IRQHandler
    .long IEL1_IRQHandler
    .long IEL2_IRQHandler
    .long IEL3_IRQHandler
    .long IEL4_IRQHandler
    .long IEL5_IRQHandler
    .long IEL6_IRQHandler
    .long IEL7_IRQHandler
    .long IEL8_IRQHandler
    .long IEL9_IRQHandler
    .long IEL10_IRQHandler
    .long IEL11_IRQHandler
    .long IEL12_IRQHandler
    .long IEL13_IRQHandler
    .long IEL14_IRQHandler
    .long IEL15_IRQHandler
    .long IEL16_IRQHandler
    .long IEL17_IRQHandler
    .long IEL18_IRQHandler
    .long IEL19_IRQHandler
    .long IEL20_IRQHandler
    .long IEL21_IRQHandler
    .long IEL22_IRQHandler
    .long IEL23_IRQHandler
    .long IEL24_IRQHandler
    .long IEL25_IRQHandler
    .long IEL26_IRQHandler
    .long IEL27_IRQHandler
    .long IEL28_IRQHandler
    .long IEL29_IRQHandler
    .long IEL30_IRQHandler
    .long IEL31_IRQHandler

    // Define default implementations for interrupts, redirecting to
    // Default_Handler when not implemented.
    IRQ NMI_Handler
    IRQ HardFault_Handler
    IRQ MemoryManagement_Handler
    IRQ BusFault_Handler
    IRQ UsageFault_Handler
    IRQ SVC_Handler
    IRQ DebugMon_Handler
    IRQ PendSV_Handler
    IRQ SysTick_Handler
    IRQ IEL0_IRQHandler
    IRQ IEL1_IRQHandler
    IRQ IEL2_IRQHandler
    IRQ IEL3_IRQHandler
    IRQ IEL4_IRQHandler
    IRQ IEL5_IRQHandler
    IRQ IEL6_IRQHandler
    IRQ IEL7_IRQHandler
    IRQ IEL8_IRQHandler
    IRQ IEL9_IRQHandler
    IRQ IEL10_IRQHandler
    IRQ IEL11_IRQHandler
    IRQ IEL12_IRQHandler
    IRQ IEL13_IRQHandler
    IRQ IEL14_IRQHandler
    IRQ IEL15_IRQHandler
    IRQ IEL16_IRQHandler
    IRQ IEL17_IRQHandler
    IRQ IEL18_IRQHandler
    IRQ IEL19_IRQHandler
    IRQ IEL20_IRQHandler
    IRQ IEL21_IRQHandler
    IRQ IEL22_IRQHandler
    IRQ IEL23_IRQHandler
    IRQ IEL24_IRQHandler
    IRQ IEL25_IRQHandler
    IRQ IEL26_IRQHandler
    IRQ IEL27_IRQHandler
    IRQ IEL28_IRQHandler
    IRQ IEL29_IRQHandler
    IRQ IEL30_IRQHandler
    IRQ IEL31_IRQHandler

.size __isr_vector, .-__isr_vector
