// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.go from rp2040.svd, see https://github.com/posborne/cmsis-svd/tree/master/data/RaspberryPi

/*

*/

//     Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
//
//     SPDX-License-Identifier: BSD-3-Clause

.syntax unified

// This is the default handler for interrupts, if triggered but not defined.
.section .text.Default_Handler
.global  Default_Handler
.type    Default_Handler, %function
Default_Handler:
    wfe
    b    Default_Handler
.size Default_Handler, .-Default_Handler

// Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, Default_Handler
.endm

// Must set the "a" flag on the section:
// https://svnweb.freebsd.org/base/stable/11/sys/arm/arm/locore-v4.S?r1=321049&r2=321048&pathrev=321049
// https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
.section .isr_vector, "a", %progbits
.global  __isr_vector
__isr_vector:
    // Interrupt vector as defined by Cortex-M, starting with the stack top.
    // On reset, SP is initialized with *0x0 and PC is loaded with *0x4, loading
    // _stack_top and Reset_Handler.
    .long _stack_top
    .long Reset_Handler
    .long NMI_Handler
    .long HardFault_Handler
    .long MemoryManagement_Handler
    .long BusFault_Handler
    .long UsageFault_Handler
    .long 0
    .long 0
    .long 0
    .long 0
    .long SVC_Handler
    .long DebugMon_Handler
    .long 0
    .long PendSV_Handler
    .long SysTick_Handler

    // Extra interrupts for peripherals defined by the hardware vendor.
    .long TIMER_IRQ_0_IRQHandler
    .long TIMER_IRQ_1_IRQHandler
    .long TIMER_IRQ_2_IRQHandler
    .long TIMER_IRQ_3_IRQHandler
    .long PWM_IRQ_WRAP_IRQHandler
    .long USBCTRL_IRQ_IRQHandler
    .long XIP_IRQ_IRQHandler
    .long PIO0_IRQ_0_IRQHandler
    .long PIO0_IRQ_1_IRQHandler
    .long PIO1_IRQ_0_IRQHandler
    .long PIO1_IRQ_1_IRQHandler
    .long DMA_IRQ_0_IRQHandler
    .long DMA_IRQ_1_IRQHandler
    .long IO_IRQ_BANK0_IRQHandler
    .long IO_IRQ_QSPI_IRQHandler
    .long SIO_IRQ_PROC0_IRQHandler
    .long SIO_IRQ_PROC1_IRQHandler
    .long CLOCKS_IRQ_IRQHandler
    .long SPI0_IRQ_IRQHandler
    .long SPI1_IRQ_IRQHandler
    .long UART0_IRQ_IRQHandler
    .long UART1_IRQ_IRQHandler
    .long ADC_IRQ_FIFO_IRQHandler
    .long I2C0_IRQ_IRQHandler
    .long I2C1_IRQ_IRQHandler
    .long RTC_IRQ_IRQHandler

    // Define default implementations for interrupts, redirecting to
    // Default_Handler when not implemented.
    IRQ NMI_Handler
    IRQ HardFault_Handler
    IRQ MemoryManagement_Handler
    IRQ BusFault_Handler
    IRQ UsageFault_Handler
    IRQ SVC_Handler
    IRQ DebugMon_Handler
    IRQ PendSV_Handler
    IRQ SysTick_Handler
    IRQ TIMER_IRQ_0_IRQHandler
    IRQ TIMER_IRQ_1_IRQHandler
    IRQ TIMER_IRQ_2_IRQHandler
    IRQ TIMER_IRQ_3_IRQHandler
    IRQ PWM_IRQ_WRAP_IRQHandler
    IRQ USBCTRL_IRQ_IRQHandler
    IRQ XIP_IRQ_IRQHandler
    IRQ PIO0_IRQ_0_IRQHandler
    IRQ PIO0_IRQ_1_IRQHandler
    IRQ PIO1_IRQ_0_IRQHandler
    IRQ PIO1_IRQ_1_IRQHandler
    IRQ DMA_IRQ_0_IRQHandler
    IRQ DMA_IRQ_1_IRQHandler
    IRQ IO_IRQ_BANK0_IRQHandler
    IRQ IO_IRQ_QSPI_IRQHandler
    IRQ SIO_IRQ_PROC0_IRQHandler
    IRQ SIO_IRQ_PROC1_IRQHandler
    IRQ CLOCKS_IRQ_IRQHandler
    IRQ SPI0_IRQ_IRQHandler
    IRQ SPI1_IRQ_IRQHandler
    IRQ UART0_IRQ_IRQHandler
    IRQ UART1_IRQ_IRQHandler
    IRQ ADC_IRQ_FIFO_IRQHandler
    IRQ I2C0_IRQ_IRQHandler
    IRQ I2C1_IRQ_IRQHandler
    IRQ RTC_IRQ_IRQHandler

.size __isr_vector, .-__isr_vector
