package convert

import (
	"bytes"
	"fmt"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/goplus/gogen"
	"github.com/goplus/llgo/chore/_xtool/llcppsymg/config/cfgparse"
	cfg "github.com/goplus/llgo/chore/gogensig/config"
	"github.com/goplus/llgo/chore/gogensig/convert/deps"
	"github.com/goplus/llgo/chore/llcppg/ast"
	cppgtypes "github.com/goplus/llgo/chore/llcppg/types"
)

const (
	DbgFlagAll = 1
)

var (
	debug bool
)

func SetDebug(flags int) {
	if flags != 0 {
		debug = true
	}
}

// -----------------------------------------------------------------------------

type Package struct {
	name      string
	p         *gogen.Package
	deps      []*deps.CPackage
	cvt       *TypeConv
	outputDir string
	conf      *PackageConfig
	depIncs   []string
	inCurPkg  bool              // whether the current file is in the llcppg package not the dependent files
	isSys     bool              // whether system header
	public    map[string]string // original C name -> public Go name
	incPaths  []string          //current pkg's include file
}

type PackageConfig struct {
	PkgPath     string
	Name        string
	OutputDir   string
	SymbolTable *cfg.SymbolTable
	GenConf     *gogen.Config
	CppgConf    *cppgtypes.Config
	Public      map[string]string
}

// When creating a new package for conversion, a Go file named after the package is generated by default.
// If SetCurFile is not called, all type conversions will be written to this default Go file.
func NewPackage(config *PackageConfig) *Package {
	p := &Package{
		p:      gogen.NewPackage(config.PkgPath, config.Name, config.GenConf),
		name:   config.Name,
		conf:   config,
		public: make(map[string]string),
	}

	p.outputDir = config.OutputDir
	p.public = config.Public

	cflags := cfgparse.ParseCFlags(config.CppgConf.CFlags)
	incPaths, _, err := cflags.GenHeaderFilePaths(config.CppgConf.Include)
	if err != nil {
		log.Println("failed to gen include paths: \n", err.Error())
	}
	p.incPaths = incPaths
	// init deps
	deps, err := deps.LoadDeps(p.outputDir, config.CppgConf.Deps)
	if err != nil {
		log.Println("failed to load deps: \n", err.Error())
	}
	p.deps = deps
	clib := p.p.Import("github.com/goplus/llgo/c")
	typeMap := NewBuiltinTypeMapWithPkgRefS(clib, p.p.Unsafe())
	p.cvt = NewConv(&TypeConfig{
		Types:        p.p.Types,
		TypeMap:      typeMap,
		SymbolTable:  config.SymbolTable,
		TrimPrefixes: config.CppgConf.TrimPrefixes,
		Deps:         deps,
		Package:      p,
	})
	p.initDepPkgs()
	p.SetCurFile(p.Name(), false, false, false)
	return p
}

func (p *Package) SetCurFile(file string, isHeaderFile bool, inCurPkg bool, isSys bool) error {
	// for system header file,avoid create a file of gogen
	if p.isSys = isSys; p.isSys {
		if debug {
			log.Printf("%s is a system header file\n", file)
		}
		return nil
	}
	var fileName string
	if isHeaderFile {
		// path to go filename
		fileName = HeaderFileToGo(file)
	} else {
		// package name as the default file
		fileName = file + ".go"
	}
	if debug {
		log.Printf("SetCurFile: %s File in Current Package: %v\n", fileName, inCurPkg)
	}
	_, err := p.p.SetCurFile(fileName, true)
	if err != nil {
		return fmt.Errorf("fail to set current file %s\n%w", file, err)
	}
	p.inCurPkg = inCurPkg
	p.p.Unsafe().MarkForceUsed(p.p)
	return nil
}

func (p *Package) GetGenPackage() *gogen.Package {
	return p.p
}

func (p *Package) GetOutputDir() string {
	return p.outputDir
}

func (p *Package) Name() string {
	return p.name
}

// todo(zzy):refine logic
func (p *Package) linkLib(lib string) error {
	if lib == "" {
		return fmt.Errorf("empty lib name")
	}
	linkString := fmt.Sprintf("link: %s;", lib)
	p.p.CB().NewConstStart(types.Typ[types.String], "LLGoPackage").Val(linkString).EndInit(1)
	return nil
}

func (p *Package) NewFuncDecl(funcDecl *ast.FuncDecl) error {
	skip, anony, err := p.cvt.handleSysType(funcDecl.Name, funcDecl.Loc)
	if skip {
		if debug {
			log.Printf("NewFuncDecl: %v is a function of system header file\n", funcDecl.Name)
		}
		return err
	}
	if debug {
		log.Printf("NewFuncDecl: %v\n", funcDecl.Name)
	}
	if anony {
		return fmt.Errorf("anonymous function not supported")
	}

	goFuncName, err := p.cvt.LookupSymbol(cfg.MangleNameType(funcDecl.MangledName))
	if err != nil {
		// not gen the function not in the symbolmap
		return err
	}
	if obj := p.p.Types.Scope().Lookup(goFuncName); obj != nil {
		return fmt.Errorf("function %s already defined", goFuncName)
	}
	sig, err := p.cvt.ToSignature(funcDecl.Type)
	if err != nil {
		return err
	}
	decl := p.p.NewFuncDecl(token.NoPos, string(goFuncName), sig)
	doc := CommentGroup(funcDecl.Doc)
	doc.AddCommentGroup(NewFuncDocComments(funcDecl.Name.Name, string(goFuncName)))
	decl.SetComments(p.p, doc.CommentGroup)
	return nil
}

// todo(zzy): for class,union,struct
func (p *Package) NewTypeDecl(typeDecl *ast.TypeDecl) error {
	skip, anony, err := p.cvt.handleSysType(typeDecl.Name, typeDecl.Loc)
	if skip {
		if debug {
			log.Printf("NewTypeDecl: %s type of system header\n", typeDecl.Name)
		}
		return err
	}
	if debug {
		log.Printf("NewTypeDecl: %v\n", typeDecl.Name)
	}
	if anony {
		if debug {
			log.Println("NewTypeDecl:Skip a anonymous type")
		}
		return nil
	}

	// every type name should be public
	name, changed, err := p.DeclName(typeDecl.Name.Name, true)
	if err != nil {
		return err
	}

	structType, err := p.cvt.RecordTypeToStruct(typeDecl.Type)
	if err != nil {
		return err
	}

	typeBlock := p.p.NewTypeDefs()
	typeBlock.SetComments(CommentGroup(typeDecl.Doc).CommentGroup)
	decl := typeBlock.NewType(name)
	decl.InitType(p.p, structType)

	if changed {
		substObj(p.p.Types, p.p.Types.Scope(), typeDecl.Name.Name, decl.Type().Obj())
	}
	return nil
}

func (p *Package) NewTypedefDecl(typedefDecl *ast.TypedefDecl) error {
	skip, _, err := p.cvt.handleSysType(typedefDecl.Name, typedefDecl.Loc)
	if skip {
		if debug {
			log.Printf("NewTypedefDecl: %v is a typedef of system header file\n", typedefDecl.Name)
		}
		return err
	}
	if debug {
		log.Printf("NewTypedefDecl: %v\n", typedefDecl.Name)
	}
	name, changed, err := p.DeclName(typedefDecl.Name.Name, true)
	if err != nil {
		// for a typedef ,always appear same name like
		// typedef struct foo { int a; } foo;
		// For this typedef, we only need skip this
		return nil
	}

	genDecl := p.p.NewTypeDefs()
	typ, err := p.ToType(typedefDecl.Type)
	if err != nil {
		return err
	}
	typeSpecdecl := genDecl.NewType(name)
	typeSpecdecl.InitType(p.p, typ)
	if _, ok := typ.(*types.Signature); ok {
		genDecl.SetComments(NewTypecDocComments())
	}
	if changed {
		substObj(p.p.Types, p.p.Types.Scope(), typedefDecl.Name.Name, typeSpecdecl.Type().Obj())
	}
	return nil
}

// Convert ast.Expr to types.Type
func (p *Package) ToType(expr ast.Expr) (types.Type, error) {
	return p.cvt.ToType(expr)
}

func (p *Package) NewTypedefs(name string, typ types.Type) *gogen.TypeDecl {
	def := p.p.NewTypeDefs()
	t := def.NewType(name)
	t.InitType(def.Pkg(), typ)
	def.Complete()
	return t
}

func (p *Package) NewEnumTypeDecl(enumTypeDecl *ast.EnumTypeDecl) error {
	skip, _, err := p.cvt.handleSysType(enumTypeDecl.Name, enumTypeDecl.Loc)
	if skip {
		if debug {
			log.Printf("NewEnumTypeDecl: %v is a enum type of system header file\n", enumTypeDecl.Name)
		}
		return err
	}
	if debug {
		log.Printf("NewEnumTypeDecl: %v\n", enumTypeDecl.Name)
	}
	enumType, enumTypeName, err := p.createEnumType(enumTypeDecl.Name)
	if err != nil {
		return err
	}
	if len(enumTypeDecl.Type.Items) > 0 {
		err = p.createEnumItems(enumTypeDecl.Type.Items, enumType, enumTypeName)
		if err != nil {
			return err
		}
	}
	return nil
}

func (p *Package) createEnumType(enumName *ast.Ident) (types.Type, string, error) {
	var name string
	var changed bool
	var err error
	var t *gogen.TypeDecl
	if enumName != nil {
		name, changed, err = p.DeclName(enumName.Name, true)
		if err != nil {
			return nil, "", fmt.Errorf("enum type %s already defined", enumName.Name)
		}
	}
	enumType := p.cvt.ToDefaultEnumType()
	if name != "" {
		t = p.NewTypedefs(name, enumType)
		enumType = p.p.Types.Scope().Lookup(name).Type()
	}
	if changed {
		substObj(p.p.Types, p.p.Types.Scope(), enumName.Name, t.Type().Obj())
	}
	return enumType, name, nil
}

func (p *Package) createEnumItems(items []*ast.EnumItem, enumType types.Type, enumTypeName string) error {
	constDefs := p.p.NewConstDefs(p.p.Types.Scope())
	for _, item := range items {
		var constName string
		// maybe get a new name,because the after executed name,have some situation will found same name
		if enumTypeName != "" {
			constName = enumTypeName + "_" + item.Name.Name
		} else {
			constName = item.Name.Name
		}
		name, changed, err := p.DeclName(constName, false)
		if err != nil {
			return fmt.Errorf("enum item %s already defined %w", name, err)
		}
		val, err := Expr(item.Value).ToInt()
		if err != nil {
			return err
		}
		constDefs.New(func(cb *gogen.CodeBuilder) int {
			cb.Val(val)
			return 1
		}, 0, token.NoPos, enumType, name)
		if changed {
			if obj := p.p.Types.Scope().Lookup(name); obj != nil {
				substObj(p.p.Types, p.p.Types.Scope(), item.Name.Name, obj)
			}
		}
	}
	return nil
}

// Write generates a Go file based on the package content.
// The output file will be generated in a subdirectory named after the package within the outputDir.
// If outputDir is not provided, the current directory will be used.
// The header file name is the go file name.
//
// Files that are already processed in dependent packages will not be output.
func (p *Package) Write(headerFile string) error {
	if p.isSys {
		return nil
	}
	fileName := HeaderFileToGo(headerFile)
	filePath := filepath.Join(p.outputDir, fileName)
	if debug {
		log.Printf("Write HeaderFile [%s] from  gogen:[%s] to [%s]\n", headerFile, fileName, filePath)
	}
	return p.writeToFile(fileName, filePath)
}

func (p *Package) WriteLinkFile() (string, error) {
	fileName := p.name + "_autogen_link.go"
	filePath := filepath.Join(p.outputDir, fileName)
	p.p.SetCurFile(fileName, true)
	err := p.linkLib(p.conf.CppgConf.Libs)
	if debug {
		log.Printf("Write LinkFile [%s] from  gogen:[%s] to [%s]\n", fileName, fileName, filePath)
	}
	if err != nil {
		return "", fmt.Errorf("failed to link lib: %w", err)
	}
	if err := p.writeToFile(fileName, filePath); err != nil {
		return "", fmt.Errorf("failed to write file: %w", err)
	}
	return filePath, nil
}

// WriteDefaultFileToBuffer writes the content of the default Go file to a buffer.
// The default file is named after the package (p.Name() + ".go").
// This method is particularly useful for testing type outputs, especially in package tests
// where there typically isn't (and doesn't need to be) a corresponding header file.
// Before calling SetCurFile, all type creations are written to this default gogen file.
// It allows for easy inspection of generated types without the need for actual file I/O.
func (p *Package) WriteDefaultFileToBuffer() (*bytes.Buffer, error) {
	return p.WriteToBuffer(p.Name() + ".go")
}

// Write the corresponding files in gogen package to the file
func (p *Package) writeToFile(genFName string, filePath string) error {
	buf, err := p.WriteToBuffer(genFName)
	if err != nil {
		return err
	}
	return os.WriteFile(filePath, buf.Bytes(), 0644)
}

// Write the corresponding files in gogen package to the buffer
func (p *Package) WriteToBuffer(genFName string) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	err := p.p.WriteTo(buf, genFName)
	if err != nil {
		return nil, fmt.Errorf("failed to write to buffer: %w", err)
	}
	return buf, nil
}

// /path/to/foo.h -> foo.go
// /path/to/_intptr.h -> X_intptr.go
func HeaderFileToGo(incPath string) string {
	_, fileName := filepath.Split(incPath)
	ext := filepath.Ext(fileName)
	if len(ext) > 0 {
		fileName = strings.TrimSuffix(fileName, ext)
	}
	if strings.HasPrefix(fileName, "_") {
		fileName = "X" + fileName
	}
	return fileName + ".go"
}

func (p *Package) WritePubFile() error {
	return cfg.WritePubFile(filepath.Join(p.outputDir, "llcppg.pub"), p.public)
}

func (p *Package) initDepPkgs() {
	allDepIncs := make([]string, 0)
	scope := p.p.Types.Scope()
	for _, dep := range p.deps {
		allDepIncs = append(allDepIncs, dep.StdIncs...)
		depPkg := p.p.Import(dep.Path)
		for cName, pubGoName := range dep.Pubs {
			if pubGoName == "" {
				pubGoName = cName
			}
			if obj := depPkg.TryRef(pubGoName); obj != nil {
				var preObj types.Object
				if pubGoName == cName {
					preObj = obj
				} else {
					preObj = gogen.NewSubst(token.NoPos, p.p.Types, cName, obj)
				}
				if old := scope.Insert(preObj); old != nil {
					log.Printf("conflicted name `%v` in %v, previous definition is %v\n", pubGoName, dep.Path, old)
				}
			}
		}
	}
	p.depIncs = allDepIncs
}

// For a decl name, if it's a current package, remove the prefixed name
// For a decl name, it should be unique
// todo(zzy): not current converter package file,need not remove prefixed name
func (p *Package) DeclName(name string, collect bool) (pubName string, changed bool, err error) {
	originName := name
	goName, ok := p.public[name]
	if ok {
		name = goName
	} else {
		if p.inCurPkg {
			name = p.cvt.RemovePrefixedName(name)
		}
		name = CPubName(name)
	}
	if obj := p.p.Types.Scope().Lookup(name); obj != nil {
		return "", false, fmt.Errorf("type %s already defined,original name is %s", name, originName)
	}
	changed = name != originName
	if collect && p.inCurPkg {
		if changed {
			p.public[originName] = name
		} else {
			p.public[originName] = ""
		}
	}
	return name, changed, nil
}

// AllDepIncs returns all std include paths of dependent packages
func (p *Package) AllDepIncs() []string {
	return p.depIncs
}
