// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/cobra/xcmd"
	"github.com/goplus/llgo/internal/env"
	"github.com/qiniu/x/stringutil"
	"runtime"
)

const _ = true

type version struct {
	xcmd.Command
	*App
}
type App struct {
	xcmd.App
}

func (this *App) Main() {
	_gop_obj0 := &version{App: this}
	xcmd.Gopt_App_Main(this, _gop_obj0)
}
//line cmd/llgo/version_cmd.gox:7
func (this *version) Main(_gop_arg0 string) {
	this.Command.Main(_gop_arg0)
//line cmd/llgo/version_cmd.gox:7:1
	this.Short("print LLGo version")
//line cmd/llgo/version_cmd.gox:9:1
	this.Run__0(func() {
//line cmd/llgo/version_cmd.gox:10:1
		fmt.Println(stringutil.Concat("llgo ", env.Version(), " ", runtime.GOOS, "/", runtime.GOARCH))
	})
}
func (this *version) Classfname() string {
	return "version"
}
func main() {
//line cmd/llgo/version_cmd.gox:9:1
	new(App).Main()
}
