name: "Setup GoReleaser"
description: "Setup GoReleaser environment"
inputs:
  linux-cache-key:
    description: "Linux sysroot cache key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Restore Linux sysroot cache
      id: cache-linux-sysroot
      uses: actions/cache/restore@v4
      with:
        path: .sysroot/linux.tar.gz
        key: ${{ inputs.linux-cache-key }}
    - name: Populate Linux sysroot
      run: tar -xzvf .sysroot/linux.tar.gz -C .sysroot
      shell: bash
    - name: Check file
      run: tree .sysroot
      shell: bash
    - name: Get Esp clang
      run: bash .github/workflows/download_esp_clang.sh
      shell: bash
