name: "Setup GoReleaser"
description: "Setup GoReleaser environment"
inputs:
  darwin-cache-key:
    description: "Darwin sysroot cache key"
    required: true
  linux-cache-key:
    description: "Linux sysroot cache key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Restore Darwin sysroot cache
      id: cache-darwin-sysroot
      uses: actions/cache/restore@v4
      with:
        path: .sysroot/darwin.tar.gz
        key: ${{ inputs.darwin-cache-key }}
    - name: Restore Linux sysroot cache
      id: cache-linux-sysroot
      uses: actions/cache/restore@v4
      with:
        path: .sysroot/linux.tar.gz
        key: ${{ inputs.linux-cache-key }}
    - name: Populate Darwin sysroot
      run: tar -xzvf .sysroot/darwin.tar.gz -C .sysroot
      shell: bash
    - name: Populate Linux sysroot
      run: tar -xzvf .sysroot/linux.tar.gz -C .sysroot
      shell: bash
    - name: Check file
      run: tree .sysroot
      shell: bash
