name: "Setup GoReleaser"
description: "Setup GoReleaser environment"
inputs:
  linux-cache-key:
    description: "Linux sysroot cache key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Restore Linux sysroot cache
      id: cache-linux-sysroot
      uses: actions/cache/restore@v5
      with:
        path: .sysroot/linux.tar.gz
        key: ${{ inputs.linux-cache-key }}
    - name: Populate Linux sysroot
      run: tar -xzvf .sysroot/linux.tar.gz -C .sysroot
      shell: bash
    - name: Restore ESP Clang cache
      id: cache-esp-clang
      uses: actions/cache/restore@v5
      with:
        path: |
          .sysroot/darwin/amd64/crosscompile/clang
          .sysroot/darwin/arm64/crosscompile/clang
          .sysroot/linux/amd64/crosscompile/clang
          .sysroot/linux/arm64/crosscompile/clang
        key: esp-clang-${{ hashFiles('.github/workflows/download_esp_clang.sh') }}
    - name: Download ESP Clang (if cache miss)
      if: steps.cache-esp-clang.outputs.cache-hit != 'true'
      run: bash .github/workflows/download_esp_clang.sh
      shell: bash
    - name: Save ESP Clang cache
      if: steps.cache-esp-clang.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          .sysroot/darwin/amd64/crosscompile/clang
          .sysroot/darwin/arm64/crosscompile/clang
          .sysroot/linux/amd64/crosscompile/clang
          .sysroot/linux/arm64/crosscompile/clang
        key: esp-clang-${{ hashFiles('.github/workflows/download_esp_clang.sh') }}
    - name: Check file
      run: tree .sysroot
      shell: bash
