// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.go from ATSAML11E14A.svd, see https://github.com/posborne/cmsis-svd/tree/master/data/Atmel

/*
// Microchip ATSAML11E14A Microcontroller
*/



.syntax unified

// This is the default handler for interrupts, if triggered but not defined.
.section .text.Default_Handler
.global  Default_Handler
.type    Default_Handler, %function
Default_Handler:
    wfe
    b    Default_Handler
.size Default_Handler, .-Default_Handler

// Avoid the need for repeated .weak and .set instructions.
.macro IRQ handler
    .weak  \handler
    .set   \handler, Default_Handler
.endm

// Must set the "a" flag on the section:
// https://svnweb.freebsd.org/base/stable/11/sys/arm/arm/locore-v4.S?r1=321049&r2=321048&pathrev=321049
// https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
.section .isr_vector, "a", %progbits
.global  __isr_vector
__isr_vector:
    // Interrupt vector as defined by Cortex-M, starting with the stack top.
    // On reset, SP is initialized with *0x0 and PC is loaded with *0x4, loading
    // _stack_top and Reset_Handler.
    .long _stack_top
    .long Reset_Handler
    .long NMI_Handler
    .long HardFault_Handler
    .long MemoryManagement_Handler
    .long BusFault_Handler
    .long UsageFault_Handler
    .long 0
    .long 0
    .long 0
    .long 0
    .long SVC_Handler
    .long DebugMon_Handler
    .long 0
    .long PendSV_Handler
    .long SysTick_Handler

    // Extra interrupts for peripherals defined by the hardware vendor.
    .long 0
    .long WDT_IRQHandler
    .long RTC_IRQHandler
    .long EIC_0_IRQHandler
    .long EIC_1_IRQHandler
    .long EIC_2_IRQHandler
    .long EIC_3_IRQHandler
    .long EIC_OTHER_IRQHandler
    .long FREQM_IRQHandler
    .long NVMCTRL_IRQHandler
    .long PORT_IRQHandler
    .long DMAC_0_IRQHandler
    .long DMAC_1_IRQHandler
    .long DMAC_2_IRQHandler
    .long DMAC_3_IRQHandler
    .long DMAC_OTHER_IRQHandler
    .long EVSYS_0_IRQHandler
    .long EVSYS_1_IRQHandler
    .long EVSYS_2_IRQHandler
    .long EVSYS_3_IRQHandler
    .long EVSYS_NSCHK_IRQHandler
    .long PAC_IRQHandler
    .long SERCOM0_0_IRQHandler
    .long SERCOM0_1_IRQHandler
    .long SERCOM0_2_IRQHandler
    .long SERCOM0_OTHER_IRQHandler
    .long SERCOM1_0_IRQHandler
    .long SERCOM1_1_IRQHandler
    .long SERCOM1_2_IRQHandler
    .long SERCOM1_OTHER_IRQHandler
    .long SERCOM2_0_IRQHandler
    .long SERCOM2_1_IRQHandler
    .long SERCOM2_2_IRQHandler
    .long SERCOM2_OTHER_IRQHandler
    .long TC0_IRQHandler
    .long TC1_IRQHandler
    .long TC2_IRQHandler
    .long ADC_OTHER_IRQHandler
    .long ADC_RESRDY_IRQHandler
    .long AC_IRQHandler
    .long DAC_UNDERRUN_A_IRQHandler
    .long DAC_EMPTY_IRQHandler
    .long PTC_IRQHandler
    .long TRNG_IRQHandler
    .long TRAM_IRQHandler

    // Define default implementations for interrupts, redirecting to
    // Default_Handler when not implemented.
    IRQ NMI_Handler
    IRQ HardFault_Handler
    IRQ MemoryManagement_Handler
    IRQ BusFault_Handler
    IRQ UsageFault_Handler
    IRQ SVC_Handler
    IRQ DebugMon_Handler
    IRQ PendSV_Handler
    IRQ SysTick_Handler
    IRQ WDT_IRQHandler
    IRQ RTC_IRQHandler
    IRQ EIC_0_IRQHandler
    IRQ EIC_1_IRQHandler
    IRQ EIC_2_IRQHandler
    IRQ EIC_3_IRQHandler
    IRQ EIC_OTHER_IRQHandler
    IRQ FREQM_IRQHandler
    IRQ NVMCTRL_IRQHandler
    IRQ PORT_IRQHandler
    IRQ DMAC_0_IRQHandler
    IRQ DMAC_1_IRQHandler
    IRQ DMAC_2_IRQHandler
    IRQ DMAC_3_IRQHandler
    IRQ DMAC_OTHER_IRQHandler
    IRQ EVSYS_0_IRQHandler
    IRQ EVSYS_1_IRQHandler
    IRQ EVSYS_2_IRQHandler
    IRQ EVSYS_3_IRQHandler
    IRQ EVSYS_NSCHK_IRQHandler
    IRQ PAC_IRQHandler
    IRQ SERCOM0_0_IRQHandler
    IRQ SERCOM0_1_IRQHandler
    IRQ SERCOM0_2_IRQHandler
    IRQ SERCOM0_OTHER_IRQHandler
    IRQ SERCOM1_0_IRQHandler
    IRQ SERCOM1_1_IRQHandler
    IRQ SERCOM1_2_IRQHandler
    IRQ SERCOM1_OTHER_IRQHandler
    IRQ SERCOM2_0_IRQHandler
    IRQ SERCOM2_1_IRQHandler
    IRQ SERCOM2_2_IRQHandler
    IRQ SERCOM2_OTHER_IRQHandler
    IRQ TC0_IRQHandler
    IRQ TC1_IRQHandler
    IRQ TC2_IRQHandler
    IRQ ADC_OTHER_IRQHandler
    IRQ ADC_RESRDY_IRQHandler
    IRQ AC_IRQHandler
    IRQ DAC_UNDERRUN_A_IRQHandler
    IRQ DAC_EMPTY_IRQHandler
    IRQ PTC_IRQHandler
    IRQ TRNG_IRQHandler
    IRQ TRAM_IRQHandler

.size __isr_vector, .-__isr_vector
